# -*- coding: utf-8 -*-
"""Build 87. The screen line states facts, and each card says what kind of firm it is.

Read as ICON business development would use it, the screen line was an argument:
"X, but Y, so Z". 202 of 248 turned on so, but or would, and a reader had to work
out the conclusion the sentence was steering toward. Each line is now one or two
facts from the card, in the order a call needs them: a printing link, the wall
method, how the plans repeat, who owns the firm and where the decision sits. The
reader draws the conclusion.

SCREEN maps a card to the first eight hex digits of the SHA-1 of the line it
replaces, then the new line. A card whose line changed upstream stops the build,
so a later fix is never overwritten by this layer. firm_types.py then sets each
card's type. Build 88 set a role and a kind here instead, and counted them in the
stat strip.
"""
import hashlib

import firm_types

BANNED = ("so", "but", "would", "could", "may", "might", "means", "route", "instead", "likely",
          "probably", "should")

SCREEN = {
    'HOU-002': ('a8374dda',
        'Reserved an ICON Titan, per The Real Deal, March 2026. Prints its Zuri Gardens homes with HiveASMBLD.'),
    'HOU-016': ('67c15a6e',
        "Prints Gulf Shore Estates with HiveASMBLD, after three conventional builds. The owner's own figures: 50 percent faster, 5 to 7 percent cheaper."),
    'HOU-017': ('b6fc2dd6',
        "Prints Avenue J with HiveASMBLD, in Houston's East End. Construction started March 2026."),
    'HOU-123': ('21aec218',
        'A division of Onsite ICF, which makes and licenses the foam block it builds with.'),
    'HOU-001': ('93795da6',
        'Builds and holds its own rental homes in Dallas, Houston and Austin. Six years on its own construction software and site robotics.'),
    'HOU-126': ('522e93c5',
        'Makes its homes and ADUs in a factory. Its price list runs from $229,000 to $569,000.'),
    'HOU-060': ('36fe1bee',
        'Two standing plan families in one southeast Houston corridor. Same trades since 1990.'),
    'HOU-061': ('53431422',
        'Four communities in one corridor, three more announced. One purchasing manager buys its materials.'),
    'HOU-073': ('5acb7f67',
        "Bought HistoryMaker Homes' Houston division and kept its plans. Its parent, Clayton Properties Group, is part of Berkshire Hathaway."),
    'HOU-168': ('f10e89cc',
        'Through HHS Residential it builds detached rental homes for Tricon, 90 to 175 a site. Its employees own it.'),
    'HOU-003': ('32715cdc',
        'Redeveloping Cuney Homes in the Third Ward, with a $50 million HUD grant. Federal procurement rewards cost and schedule.'),
    'HOU-130': ('b42c3d1e',
        'Develops its own land through Woodmere Development. Sells job-built production methods as a control advantage.'),
    'HOU-074': ('005b0101',
        'One standardized entry-level product. Entered Houston by buying Devon Street Homes in 2023.'),
    'HOU-131': ('9e856ded',
        'Named plans repeat across its communities. One vice president holds construction and purchasing.'),
    'HOU-010': ('a4213cb6',
        'Builds and holds rental homes across 115-plus communities. Keeps a bank of 25,000 to 35,000 lots.'),
    'HOU-022': ('e98bea3e',
        'Daiwa House, which builds industrially in Japan, holds 80 percent. Also builds in Arizona, Tennessee and Alabama.'),
    'HOU-136': ('6846d4f8',
        'Repeats three, four and five bedroom rental plans. Part of industrial developer Clay Development & Construction.'),
    'HOU-122': ('8ed2f169',
        'Builds every wall, floor and roof in one concrete panel system. Each house is designed for its site.'),
    'HOU-007': ('54c0fbfc',
        'Markets its own framed wall assembly. Its parent is The Signorelli Company, and John Winniford became president in September 2025.'),
    'HOU-004': ('d8613f89',
        'Its townhomes repeat across inner Houston and three more cities, including Dallas and Austin. Lovett Commercial, under common ownership, made POST Houston.'),
    'HOU-127': ('193ecb41',
        'Buys finished factory homes, delivered to the lot. Its Pearland community has 420 homes on 55 acres.'),
    'HOU-125': ('e39e42d6',
        'Designs custom houses one at a time. Its predecessor compared seven wall systems before choosing one.'),
    'HOU-124': ('f2924074',
        'Builds custom beach houses on Galveston Island. States coastal reasons for its wall change.'),
    'HOU-135': ('d2fd5daf',
        "Sells one plan set for buyers' own lots across Texas. Its published wall specification is stick frame."),
    'HOU-068': ('6354caae',
        'Repeats plans across six masterplans. Builds only in Houston and Austin.'),
    'HOU-064': ('3eee42ca',
        'Sells one standard plan set on no-haggle pricing, from Katy and Cypress to Splendora.'),
    'HOU-076': ('6555ea4e',
        'A David Weekley Homes line selling a curated plan set. Purchasing sits with the national builder.'),
    'HOU-071': ('7044629b',
        'Builds across sixteen communities, Sienna among them. Publishes an eight to ten month build, design to completion.'),
    'HOU-063': ('791c6409',
        'Most of its communities sit on the Lake Conroe corridor. Sells from the $300,000s to the $800,000s.'),
    'HOU-066': ('82b541c1',
        'Builds on lots scattered across six Inner Loop neighborhoods. Runs land through final inspection in house.'),
    'HOU-062': ('7d2855b9',
        'Plan repetition is its operating model. Founded in 2020 by people from Taylor Morrison, Toll Brothers and Ryland Homes.'),
    'HOU-128': ('f8409677',
        'Its founder says the future is printed concrete houses. It operates in 16 cities, overseeing more than 15 million square feet.'),
    'HOU-020': ('6da35ae9',
        'Its parcHAUS program targets seven rental communities across Texas. The firm is run from Dallas.'),
    'HOU-075': ('dccb3957',
        'Sells in Houston at Sunterra. None of its ten division presidents is in Houston.'),
    'HOU-026': ('d40f802d',
        'Built its Cypress community with Taylor Morrison. Bought Cottage Green in Conroe in October 2024.'),
    'HOU-033': ('d7a2cb9f',
        'A Dream Finders Homes brand. Its Houston division president carries DFH in his title.'),
    'HOU-069': ('05230cce',
        'Publishes 97 floor plans across Houston and Austin. Keeps one-off work in a separate custom division.'),
    'HOU-077': ('44ce3815',
        'One plan catalog serves all four of its markets. Houston is a secondary market run from San Antonio.'),
    'HOU-035': ('3e5fecf9',
        "Works in Houston's Near Northside, all of it, since 2002. Mary Lawler has led it for twenty-five years."),
    'HOU-045': ('7b334a96',
        'Folded into Sekisui House U.S. in January 2026, as its parent merges its US brands into one company.'),
    'HOU-067': ('9aecc6b9',
        'Sells from the $370,000s to the $900,000s, at Sienna, Jordan Ranch and Artavia. Names its purchasing manager.'),
    'HOU-044': ('b96ac66c',
        'Builds rental duplexes in Katy, on Galileo Way and at Clay Road. Names three construction directors and a purchasing manager.'),
    'HOU-070': ('01563d29',
        'Sells semi-custom homes in the north and northwest corridor. Its founding brothers were division presidents at Perry Homes.'),
    'HOU-028': ('3982e165',
        'Its own affiliates served as architect and general contractor at Fort Bend Town Center. Active since 1984.'),
    'HOU-152': ('a15de9ae',
        'Framed McCann Park in Houston and self-performs the framing. Engineering and fabrication are in house.'),
    'HOU-146': ('ffddf42d',
        "Sells CNC-made wall panels to Texas home builders against stick framing. On Houston's registered fabricator list."),
    'HOU-139': ('6f4c5d4f',
        "Casts stormwater, manhole, LNG and data center precast. Also makes precast at the customer's premises or jobsite."),
    'HOU-120': ('5966468b',
        'Sets insulated concrete form walls with its own full-time crews, for custom homes, condominiums and light commercial.'),
    'HOU-104': ('7fe4831d',
        'Self-performs foundations, tilt-up walls and slabs from one Houston yard. Began on residential work, then moved to commercial.'),
    'HOU-156': ('7e316fdd',
        'Runs a 7,700 square foot fabrication facility for prefabricated wall systems. Its site says it is looking for new prefabricated materials.'),
    'HOU-101': ('e8a0cf72',
        'Owns its pumps, booms, formwork and tower cranes. Its residential division works custom home foundations and master plan communities.'),
    'HOU-121': ('836d5d25',
        'Its walls are interior drywall assemblies, some prefabricated in its own warehouse. Separate multifamily and single family divisions.'),
    'HOU-162': ('81a4853b',
        'Shoots gunite and shotcrete through a nozzle for retaining walls, pools and tunnels. Works from Houston, Dallas, Austin, San Antonio and Los Angeles.'),
    'HOU-143': ('077d6a07',
        'Casts commercial and data center precast, plus modular cells, in San Antonio. Its general manager wants to widen what the plant makes.'),
    'HOU-129': ('040469a9',
        'Delivered a printed house in Spring Branch with a printing contractor and an architect. Each design-build project is different.'),
    'HOU-157': ('20a6f1c6',
        'Laid masonry at Minute Maid Park and Reliant Stadium. Multi-family is one of eight sectors it works.'),
    'HOU-137': ('a937cbbd',
        'Casts wall panels, shear walls, beams and columns off site. Eight certified product lines share the same beds.'),
    'HOU-117': ('e0e7e226',
        'Builds garden-style and mid-rise apartments across Texas markets from its Houston headquarters. Lists 200-plus projects.'),
    'HOU-147': ('3f164a0a',
        "Its Conroe and Cut N Shoot plants make trusses and wall panels. In August 2026 it agreed to buy PulteGroup's off-site framing producer."),
    'HOU-155': ('156faa6e',
        'Lays load-bearing masonry as well as veneer, in brick, block and stone. Publishes annual revenue of 20 to 40 million dollars.'),
    'HOU-141': ('73858cbe',
        'Casts parking garage, cladding and total precast buildings in Cedar Park. Houston is a sales territory.'),
    'HOU-106': ('5c241c38',
        'Pours tilt-up and post-tensioned decks for general contractors. Part of the Satterfield and Pontikes family.'),
    'HOU-102': ('30e4067f',
        'Self-performs formwork, rebar, tiltwall and precast through IQI Construction. Builds apartments and senior living.'),
    'HOU-142': ('81f4b315',
        'Casts prestressed elements for highway, marine, industrial and stadium work. Metromont bought it on 15 December 2025.'),
    'HOU-112': ('a63eff0a',
        'Places and finishes tilt-up for institutional and commercial jobs. Its purchasing runs through a listed parent.'),
    'HOU-151': ('6389eab6',
        'Makes interior and exterior wall panels at plants in San Antonio, Taylor and Van Alstyne. The Texas banner for US LBM.'),
    'HOU-149': ('f81b4090',
        'Makes wall panels, floor cassettes and trusses for regional builders. Its parent argues wall panels need fewer people on site.'),
    'HOU-144': ('b0385b5e',
        'Casts architectural and structural wall, double tees and shear walls in two plants. Runs 30-plus projects a year.'),
    'HOU-138': ('f7f13c0e',
        'Makes one product, hollowcore floor and roof plank. KPS Capital Partners agreed in February 2026 to buy its parent.'),
    'HOU-105': ('fe277036',
        "Poured the tilt-up panels on Arch-Con's award-listed job in Humble, 32 panels across four floors."),
    'HOU-145': ('3635e1d7',
        'Casts parking structures, commercial buildings and multi-family elements at one San Antonio plant. Counts more than 20 HEB stores.'),
    'HOU-114': ('f994d943',
        'Builds tilt-up warehouses, offices, healthcare and church jobs across Houston and Central Texas. Formerly Rosenberger Construction.'),
    'HOU-165': ('7004a77d',
        'Works from one Conroe office, in the north Houston growth corridor. Its published projects are commercial.'),
    'HOU-161': ('62f07c48',
        'Pumps concrete for home builders and contractors from one Kingwood office. Runs boom pumps from 32 to 65 meters.'),
    'HOU-103': ('91a80da3',
        'Supplies, forms, places and finishes its own concrete. Its jobs run $500,000 to $15 million.'),
    'HOU-140': ('3bae9498',
        'Casts bridge, highway and industrial precast at two Texas plants. Serves petrochemical, LNG, pipeline and power.'),
    'HOU-150': ('a5fdc2a7',
        "Makes wall panels for production builders at Caldwell, 90 minutes from Houston. On Houston's registered fabricator list."),
    'HOU-159': ('2e677cc9',
        'Lays load-bearing block for hospitals, colleges and fire stations across Greater Houston and Galveston, with its own superintendents and foremen.'),
    'HOU-158': ('517f27c0',
        'Lays face brick, cast stone and concrete masonry across education, healthcare and residential projects. Runs projects all over town at once.'),
    'HOU-164': ('c3e5bead',
        'Repeats work in the same Houston submarkets from a single Tomball office. A Greater Houston Builders Association Distinguished Member.'),
    'HOU-153': ('6c817f63',
        'Makes and installs steel stud, truss packages and prefab walls on a single line. Residential on request.'),
    'HOU-113': ('d88d0960',
        'Runs a Houston industrial office inside a national firm of 12,500-plus people. Purchases run through a national desk.'),
    'HOU-160': ('bba8af43',
        "Places other firms' concrete with its own pumps, conveyors and telebelts, from two Houston yards."),
    'HOU-163': ('91f5753f',
        'Pours foundations for production builders. D.R. Horton has taken more than 2,000 of its home foundations.'),
    'HOU-148': ('b3091126',
        'Sells prefabricated wall panels to Houston multifamily builders. Its parent is Builders FirstSource.'),
    'HOU-118': ('9d2f8d15',
        'Sells the whole wall package to production builders. Uses over 900 subcontractors and owns almost no field labor.'),
    'HOU-115': ('30513818',
        'Buys its concrete rather than pouring it. Encore Concrete Construction poured its award-listed tilt-up panels.'),
    'HOU-111': ('f7aad797',
        'Models its concrete work in three dimensions before pouring. Its work page names two multifamily buildings.'),
    'HOU-119': ('2ebe9ff2',
        'Builds prefabricated metal, tilt-wall and masonry buildings on the Gulf Coast. Also installs gantry and bridge cranes.'),
    'HOU-109': ('1b4e7d16',
        "Delivers its own concrete on volumetric mixers through Taylor Made Concrete. Builds tilt-wall buildings on the metro's east side."),
    'HOU-107': ('61ca29af',
        'Its own crews pour slabs and run site utilities on Houston housing jobs.'),
    'HOU-116': ('cbca9040',
        'Builds office, mixed-use, medical and industrial work in four metros. Won a 2024 Tilt-Up Achievement Award.'),
    'HOU-108': ('5d5a7332',
        'Pours tilt-wall panels and paving for commercial shells, with jobs in Cypress and Pearland.'),
    'HOU-110': ('c2388bce',
        "Designs and pours commercial concrete and metal buildings on the metro's north side. Its residential line pours driveways and retaining walls."),
    'HOU-006': ('ce54b5e8',
        'Develops three-story garden-style housing at Aliana in Fort Bend. Bought M-K-T Heights in March 2026 with MetroNational and Radom Capital.'),
    'HOU-072': ('3d789c7b',
        "Builds one-of-a-kind homes on buyers' lots in Houston, Dallas, the Brazos Valley and Nashville. Has a vice president of purchasing."),
    'HOU-083': ('c14e2e8e',
        'Repeats small retail buildings in the Heights, San Antonio and Austin.'),
    'HOU-005': ('0b8a25f5',
        "Fifteen projects in the Heights, each its own adaptive reuse or retail building. Its architect, Michael Hsu, also drew ICON's printed homes at Mueller."),
    'HOU-081': ('45290806',
        'Develops East Blocks, ten contiguous EaDo blocks, in a joint venture. Its build-to-rent line is outside Houston.'),
    'HOU-036': ('dfe00e6f',
        'Develops East River, the former turning-basin site on Buffalo Bayou, phased over decades. The Laura, 359 apartments, opened in 2024.'),
    'HOU-037': ('962ca76e',
        'Converts industrial buildings at Sawyer Yards, home to over 600 creative tenants.'),
    'HOU-082': ('cf01c391',
        "Develops ground-up Class A medical office and retail in Katy. Pagewood's joint-venture partner on East Blocks."),
    'HOU-038': ('573b8510',
        'Manages the Esperson towers, which Interra Capital Group bought after MetLife foreclosed in August 2024.'),
    'HOU-080': ('dc59011f',
        'Converts a former W-K-M warehouse campus into a walkable district. A partner designs in house.'),
    'HOU-132': ('e50e0c75',
        'Invested in Apis Cor, a maker of construction 3D printers, in March 2024. Closed 84,863 homes company-wide in fiscal 2025.'),
    'HOU-167': ('84b9e3f8',
        "Piloted FBR's Hadrian X robotic wall system in February 2025. Its chief executive wants to use new building methods, not operate them."),
    'HOU-009': ('abef2d22',
        'Mirabella puts 1,200 homes on 18 floor plans at one Brookshire site. Reported a company-record 112-day cycle in Q2 2026.'),
    'HOU-134': ('ad3ea784',
        'One plan library across six states, for sale and for rent. Ranked 25th on the 2026 Builder 100.'),
    'HOU-014': ('fa5f1a97',
        'One systematic entry-level plan set, bought through a national purchasing function. Headquartered in The Woodlands.'),
    'HOU-012': ('ddf28255',
        'Plans 1,000 homes at Trinity Landing with Meritage Homes. Buys centrally, under a named Houston division president.'),
    'HOU-008': ('cc21805d',
        'Plans 1,000 homes at Trinity Landing, co-acquired with M/I Homes. Buys through a corporate purchasing desk.'),
    'HOU-025': ('55ac5c98',
        'Runs Yardly, a national build-to-rent brand. Built its Cypress rental community with Christopher Todd Communities.'),
    'HOU-024': ('192d16ee',
        'Founded in Houston, now headquartered in Alpharetta. Purchasing is a corporate function, with a named Texas regional president.'),
    'HOU-023': ('bbb2a4f5',
        'Named suppliers for the whole envelope in its 2026 partner list. Its purchasing vice president, John Schiegg, is quoted there.'),
    'HOU-013': ('80bc8bca',
        'Defines innovation as smart-home features and floor plans. Builds in four Texas markets and, since February 2024, five in Florida.'),
    'HOU-034': ('1a81f85c',
        'Its parent, Sumitomo Forestry, bought a sawmill in 2025 to supply wood framing across DRB. Builds at The Woodlands Hills.'),
    'HOU-011': ('c00272f8',
        'Sells finished lots in The Woodlands, Bridgeland and The Woodlands Hills. Paid for One Bridgeland Green, a mass timber office.'),
    'HOU-015': ('58b72ed5',
        'Owns First America Homes, and one president, John Winniford, runs both. Develops Austin Point and Valley Ranch.'),
    'HOU-041': ('2aea4ca9',
        'Owns Caldwell Homes, its own builder, a separate record on this deck. The Highlands has thirteen builders.'),
    'HOU-133': ('f51f619a',
        'Developed Wolf Ranch in Georgetown, where ICON printed 100 homes for Lennar. Its Houston masterplans are Pomona, Valencia and Legacy.'),
    'HOU-039': ('c06a6545',
        'Starwood Capital took a majority interest on December 29, 2021. Its own page puts Sunterra at 1,039 acres.'),
    'HOU-040': ('ab2a6c29',
        'Sells lots to the builders on its land, Sienna among its masterplans.'),
    'HOU-043': ('c52d80b6',
        'Its leadership page now redirects to Brookfield Residential. The one Houston name on record is from 2019.'),
    'HOU-166': ('e9931e32',
        'Built the 100-home Wolf Ranch with ICON. Its division president controls home design and construction.'),
    'HOU-042': ('9594e398',
        'A wholly owned Lennar subsidiary since 2000, founded in 1962.'),
    'HOU-078': ('d6bbe2c2',
        'A Katy builder of entry-level and move-up homes. Its last published figure is 185 closings in 2016.'),
    'DFW-BTR-010': ('1b5bd996',
        'Plans over ten more communities with Centurion American, potentially over 1,000 homes. Runs its own construction software.'),
    'DFW-020': ('ba96dac5',
        'Builds some structural elements off-site, per a 2024 trade profile. A fifth-generation family firm, building since 1949.'),
    'DFW-032': ('e7ce86c9',
        'Nine master-planned communities in Frisco and Prosper. John Landon is owner and CEO.'),
    'DFW-026': ('4a1238b6',
        'Repeats production plans from Aledo to Celina. Family-owned, in its third generation.'),
    'DFW-027': ('05bc613b',
        'Family-owned, with owner and CEO Scott Sandlin the named decision-maker.'),
    'DFW-BTR-001': ('ad247c9f',
        'Builds its own rental homes through the AMH Development Program. A national single-family rental REIT.'),
    'DFW-003b': ('58b32018',
        'One townhome plan library across DFW. Its president, Steve Schermerhorn, runs three Green Brick brands.'),
    'DFW-003d': ('5a2d3a7a',
        'Makes day-to-day decisions locally. Green Brick supplies its centralized purchasing.'),
    'DFW-BTR-005': ('a7496ec4',
        'Repeats Avilla plans across 16 DFW neighborhoods. Its directory names a National Purchasing Manager and a director of construction.'),
    'DFW-014': ('874fccb0',
        'Builds at Painted Tree, among other DFW communities. Its president, Steve Schermerhorn, also runs CB JENI.'),
    'DFW-045': ('4743c984',
        'Repeats plans in Celina, Little Elm, Forney, Rockwall and the Justin corridor. Part of the Qualico family.'),
    'DFW-003c': ('a197b426',
        'Builds at The Reserve at Watters, Painted Tree and Windsong Ranch. Its president, Steve Schermerhorn, also runs CB JENI and Normandy.'),
    'DFW-003a': ('557ab3cd',
        'Its DFW cycle time is under 90 days. Land and purchasing sit at the parent.'),
    'DFW-079': ('1fad7d93',
        'Returned to DFW in 2023 with lots under contract across North Texas. Sells one repeated floor-plan catalog.'),
    'DFW-BTR-006': ('c15101f5',
        'Develops, builds and operates its own rental communities. Headquartered in San Antonio, moved from Costa Mesa.'),
    'DFW-029': ('791412e9',
        'Every home is HERS-rated by an independent energy rater. Family and employee-owned, with a sister brand, Belclaire.'),
    'DFW-078': ('609ceb64',
        'Repeats one attached-townhome plan library across DFW, from McKinney to Crowley. Bruno Pasquinelli founded it.'),
    'DFW-BTR-008': ('b9a5f505',
        'Develops and rents homes across Texas through SimplyHome. Named Dan Miller Chief Executive Officer on August 4, 2025.'),
    'DFW-037': ('4964e458',
        'One plan library, including the Essex, west and south of Fort Worth. Its team page names CEO Joey Goss and two vice presidents.'),
    'DFW-BTR-009': ('f9dfe529',
        'Curve Development developed it under its Cyrene brand, inside Painted Tree in McKinney. Detached three- and four-bedroom rentals.'),
    'DFW-008': ('f3f5f807',
        'Locally owned, with no parent company above it. Sister brands: Gallery Custom Homes and Harwood Homes.'),
    'DFW-023': ('7997a79a',
        'Frames 2x6 exterior walls and certifies every home ENERGY STAR. Stephen Brooks founded it in 1986.'),
    'DFW-035': ('4274180f',
        'Repeats villa and townhome plans inside Windsong Ranch in Prosper. Its two founders direct the business.'),
    'DFW-BTR-007': ('17c6627f',
        'Builds single-family rental homes for clients under its BUILD model. A Tricon Residential release names it builder partner.'),
    'DFW-043': ('9f4b2634',
        'Sells its own design and build-tracking software with each home. Its about page names a Texas Regional President.'),
    'DFW-021': ('c22f6694',
        'Locally owned in Southlake. Builds attainable homes in Tarrant, Denton, Kaufman, Rockwall and Johnson counties.'),
    'DFW-034': ('3f885a69',
        'Repeats named plans such as Madrid and Athens across DFW and Waco. Employee-owned through an ESOP since 2020.'),
    'DFW-022': ('b5c20f71',
        'Builds its own homes inside lagoon-amenity masterplans it controls. Repeats single-family and townhome plans.'),
    'DFW-031': ('ae441566',
        'Partners In Building, a Houston custom builder, bought it in February 2022. Its last listed community, in Garland, is closed out.'),
    'DFW-044': ('ce619448',
        'One of six Phase 1 builders signed at Serenade in Celina. Its models there target 2027.'),
    'DFW-033': ('5b00aff2',
        'Repeats one floor-plan library across more than 25 active and coming communities. Founder Tim Fleet is president.'),
    'DFW-038': ('d0363d35',
        'An Ashton Woods brand repeating streamlined plans across DFW. Purchasing sits with the parent.'),
    'DFW-030': ('02816ad9',
        'Repeats one plan library in Pilot Point, Lavon, Anna and other towns. Family-owned, established in 2010 in Melissa.'),
    'DFW-081': ('0c4ab4b1',
        'Builds production and semi-custom plans at Light Farms, Windsong Ranch and Brookhollow. Co-founder Bill Darling sold Darling Homes to Taylor Morrison in 2013.'),
    'DFW-028': ('59518e30',
        'Repeats 40 floor plans across its Texas communities, from Celina to Waxahachie.'),
    'DFW-024': ('fe420f06',
        'The luxury brand of Perry Homes, building in Plano, Frisco, Celina and Highland Village.'),
    'DFW-042': ('6d5ddb8f',
        'A Dream Finders Homes brand. Builds at Painted Tree in McKinney and at Ramble in Celina.'),
    'DFW-073': ('7cfa735c',
        'Sells a plan library with custom selections on 100-foot lots. Trades as Sanders Custom Builder, LLC.'),
    'DFW-025': ('38fc5bf6',
        'Its plans repeat, semi-custom and premium, across many North Dallas communities. Peter Shaddock and the next generation lead it.'),
    'DFW-TR-051': ('b916093a',
        'Builds ICF and concrete walls across North Texas. Family-owned, based in Bells.'),
    'DFW-TR-074': ('27ff7a0b',
        'Sells factory-made wall, floor and roof kits against stick framing. Ships about 200 miles, taking in DFW.'),
    'DFW-TR-050': ('f12753ef',
        'Sets ICF walls on DFW custom and light commercial jobs. Mark Womack acquired it in 2010.'),
    'DFW-TR-092': ('91d985b9',
        'Makes metal, EIFS and StoPanel brick panels for commercial envelopes. Built panels for the Medical City Tower Expansion in Plano.'),
    'DFW-TR-091': ('8ce881d2',
        "Builds light-gauge exterior wall panels offsite for commercial and institutional jobs. Cut a school's schedule by 60 percent, by its own account."),
    'DFW-TR-040': ('d5d43e12',
        'Makes prefabricated wall systems in a 7,700 square foot facility. Rob Barnes became president and CEO in 2015.'),
    'DFW-TR-093': ('2d6cdc83',
        'Builds structural insulated panel envelopes on luxury homes, alongside geothermal and roofing divisions.'),
    'DFW-TR-012': ('5c015b7b',
        'Supplies DFW builders from a national components line. Purchasing runs through corporate.'),
    'DFW-TR-010': ('e98135cc',
        'Makes wall panels and trusses for production builders in Hurst, Arlington and around DFW. One plant under a national purchasing desk.'),
    'DFW-TR-031': ('1961006e',
        'Casts architectural and structural precast in Central Texas since 1988. DFW is a sales territory.'),
    'DFW-TR-026': ('bbdbd711',
        'Builds tilt-wall shells across Texas. Counts more than 700 employees.'),
    'DFW-TR-032': ('94116f85',
        'Prestressed wall panels are its normal product, from San Marcos and Corpus Christi. Metromont acquired it effective December 15, 2025.'),
    'DFW-TR-085': ('cf765b95',
        'Pours post-tensioned slabs for production builders. Part of ERW Companies, with Eric Dyess as president.'),
    'DFW-TR-064': ('c6313444',
        'Pours tilt-wall, schools and paving from Euless and Arlington. Invests in LiDAR, robotics and new equipment.'),
    'DFW-TR-030': ('c15a27c2',
        'Its precast panels go to Dallas residential and civic jobs. Wells runs the plants after buying GATE Precast in July 2024.'),
    'DFW-TR-002': ('d0a8a99f',
        'Pours foundations, paving and streets for residential communities. High Street Capital announced an investment in August 2026.'),
    'DFW-TR-086': ('4d7bf6c5',
        'Lays brick, block, stone and stucco walls on DFW commercial and retail jobs.'),
    'DFW-TR-083': ('900aae5c',
        'Lays brick and stone for DFW homeowners, with repair, stucco and hardscape. Claims over 10,000 homeowners served.'),
    'DFW-TR-081': ('a714faba',
        'Builds new masonry walls and restores old ones for HOAs, property managers and general contractors.'),
    'DFW-TR-084': ('1cdb3d6a',
        'Pours slabs and flatwork for DFW builders and homeowners. Owned by Josh Lavelle and Daneel Nortier, PE.'),
    'DFW-TR-089': ('bdd9e52e',
        'Lays brick, stone and CMU and applies stucco for residential, multifamily and commercial builders.'),
    'DFW-TR-082': ('d10bb090',
        'Builds brick, stone, block and precast panel enclosures for builders and homeowners across DFW.'),
    'DFW-TR-088': ('113f85a2',
        'Lays brick and stone on new homes in Dallas County and nearby cities.'),
    'DFW-TR-042': ('7f37e5c4',
        'Lays structural CMU, brick veneer and stone, mostly on commercial and institutional jobs. David Grzesiak is President.'),
    'DFW-TR-079': ('8880b985',
        'Casts and erects tilt-wall panels as one scope, from panel layout to envelope turnover.'),
    'DFW-TR-090': ('66d31962',
        'Installs brick and stone veneer on new custom homes, alongside repair work, in Grapevine and Colleyville.'),
    'DFW-TR-071': ('9ac2c5bb',
        'Lays brick, stone and block exteriors on new homes and light commercial jobs across DFW.'),
    'DFW-TR-087': ('0ca10fbd',
        'Supplies post-tension slabs for production and custom builders, with a Houston office. Derek Tuttle is President.'),
    'DFW-TR-022': ('d7336aa9',
        'Builds K-12, municipal, medical and faith projects from Fort Worth. Mike Freeman bought the company in 2005, and purchasing sits with the family.'),
    'DFW-TR-020': ('ca3cad7d',
        'Casts and erects tilt-wall panels on site for commercial and industrial shells. Warren Nugent is owner, founder and CEO.'),
    'DFW-TR-041': ('34d52473',
        'Installs masonry and precast on commercial projects across the Metroplex. Brothers Farris and Dan Wilks founded it.'),
    'DFW-TR-025': ('841fb7b3',
        'Manages commercial construction for Austin Industries. Its purchasing is institutional.'),
    'DFW-TR-027': ('7f94f0d1',
        'Pours tilt panels and structural concrete nationally, with its Texas jobs mostly in Houston. Machine purchases run through a national desk.'),
    'DFW-TR-060': ('bc3ad4a8',
        'Pumps and places concrete for other firms from a Dallas branch. Its parent is Concrete Pumping Holdings.'),
    'DFW-TR-023': ('c1a8f967',
        'Self-performs concrete and formwork for high-rises, hotels and stadiums. Runs a 25-acre formwork yard in Dallas.'),
    'DFW-TR-024': ('8bbf693e',
        'The Dallas arm of a national group, building commercial, institutional and sports work.'),
    'DFW-TR-021': ('7be2f706',
        'Builds tilt-wall and industrial shells across Texas. Purchasing is corporate.'),
    'DFW-TR-001': ('831fe896',
        'Pours foundations for DFW production builders in 20-plus communities. A subsidiary of Sterling Infrastructure.'),
    'DFW-TR-011': ('100b5e7c',
        'Makes trusses and wall panels for DFW builders. Part of UFP Industries, with corporate purchasing.'),
    'DFW-047': ('d235c219',
        'Builds custom homes in the Lewisville and Plano area. A 2014 DOE case study names Steve Brown as its head.'),
    'DFW-048': ('4ea511e7',
        "Builds one-of-a-kind homes on buyers' lots. Entered Dallas in 2022 by buying Paul Taylor Homes."),
    'DFW-001': ('b38017f5',
        'Invested in Apis Cor, a maker of construction printing robots, in March 2024. Runs three DFW divisions: Central, East and West.'),
    'DFW-007': ('e8bca0ef',
        'Owned a framing plant and piloted a robotic wall. Materials are negotiated nationally or regionally.'),
    'DFW-061': ('1559d5b0',
        'Run from Houston under Daiwa House ownership. Sells Cobalt, Silver and Gold plan collections.'),
    'DFW-011': ('d670d152',
        'Repeats a national plan library across 67 DFW communities. Its chief operating officer once ran Dallas.'),
    'DFW-010': ('ad0b7a9b',
        'Run from Houston, with purchasing across several markets. Builds in Houston, Austin, Dallas-Fort Worth and San Antonio.'),
    'DFW-052': ('6c82f452',
        'A national public builder, buying at a national desk. Sells from Fate and Forney to Celina and Justin.'),
    'DFW-063': ('df1b0ea9',
        "PulteGroup's affordable brand, buying through PulteGroup's national desk. Sells at Townsend Green in Denton and Arbordale in Forney."),
    'DFW-060': ('8a1efb92',
        'Purchasing sits above the metro. Cut direct costs 5 percent in Q2 2026 with no change of method.'),
    'DFW-064': ('a6c22e76',
        "Buys through PulteGroup's national desk. Repeats active-adult plan collections across its Dallas market page."),
    'DFW-003': ('9cdabfa3',
        'Runs five DFW builder brands, Trophy Signature, CB JENI and Southgate among them, with land acquisition and development run centrally.'),
    'DFW-058': ('9e011d8f',
        'Repeats production plans in Haslet, Fort Worth, Van Alstyne and Providence Village. Buys at a national desk.'),
    'DFW-050': ('9ed4b9da',
        'Opened Elevon in Lavon in June 2026. Buys at a national desk.'),
    'DFW-054': ('6c48d723',
        'Buys at its corporate desk in The Woodlands. Repeats entry-level plans in Forney and Dallas.'),
    'DFW-055': ('8877af4d',
        'Buys at a national desk. Builds at Verandah in Royse City.'),
    'DFW-062': ('80925ead',
        'Builds across several US metros, buying above its Dallas Division. Sells in Justin, Celina, Forney and Gunter.'),
    'DFW-006': ('37c81a92',
        'Sells a national energy-efficient plan library across DFW. Its record stresses efficiency and cycle time.'),
    'DFW-053': ('6c72c3e7',
        'One plan library across its Dallas division, from Justin to Crandall. Buys at a national desk.'),
    'DFW-051': ('ac68de4a',
        'Luxury plans repeat at Prestwick Grove in Frisco and Wildflower Ranch. Buys at a national or division desk.'),
    'DFW-009': ('2adfcb81',
        'Purchasing is a corporate function, under a named Senior Vice President of Purchasing. One regional president covers Texas.'),
    'DFW-059': ('d83830dc',
        'Builds three districts at Painted Tree in McKinney. Buys at a national desk, on a platform shared across many metros.'),
    'DFW-CH-015': ('66c075d0',
        'Sells lots to Coventry, Highland, Perry and UnionMain. Cambridge Companies, owned by Debbie Wilson, develops it.'),
    'DFW-CH-021': ('2a26f394',
        'Sells lots to production builders including Horton, Lennar, Pulte and Ashton Woods. Formed a build-to-rent joint venture with Wan Bridge in 2025.'),
    'DFW-CH-001': ('580546c4',
        'Developed Wolf Ranch in Georgetown, where ICON printed 100 homes for Lennar. Develops Liberty and Ramble in DFW.'),
    'DFW-CH-018': ('593ca0b5',
        'Sells lots to builders such as HistoryMaker, First Texas and Chesmar. Twin brothers Phillip and Don Huffines founded it in 1985.'),
    'DFW-CH-003': ('7b524e92',
        'Sells lots at Fields to Landon Homes and to the custom builders at the Preserve. Co-develops Fields with Karahan Companies.'),
    'DFW-CH-014': ('958cc241',
        'Sells lots at Trinity Falls, Viridian and Cole Ranch, each with several builders. Michael Smith is President and Chief Executive Officer.'),
    'DFW-CH-008': ('c8b06b66',
        'Shaddock is the builder remaining in its final opportunities. Republic develops it for LFC Land Company.'),
    'DFW-CH-020': ('957b9d1f',
        'Its October 2025 fact sheet lists M/I Homes as the current builder. A Hillwood Communities masterplan.'),
    'DFW-CH-016': ('27b64389',
        'Its builders include Homebound. Tellus Group develops it, just north of Windsong Ranch.'),
    'DFW-CH-004': ('ad633ade',
        'Sells lots to David Weekley, Drees and Tri Pointe, among others, and to Cyrene for rentals.'),
    'DFW-CH-007': ('08f26b0f',
        'Roster builders: American Legend, Coventry, Drees, Highland and Perry. Hillwood develops the lots.'),
    'DFW-CH-002': ('f7a765aa',
        'Develops Walsh in Fort Worth and Light Farms in Celina, selling lots to roster builders. Co-CEOs Tony Ruggeri and Jake Wagner run it.'),
    'DFW-CH-011': ('f650a4c6',
        'Huffines sells lots to six builders, HistoryMaker and UnionMain among them. Broke ground on 24 March 2026.'),
    'DFW-CH-019': ('38cf9aef',
        'Huffines sells lots to several builders. Its Headquarters Club covers 8 acres.'),
    'DFW-CH-009': ('55d74369',
        'Five named builders, American Legend to Toll Brothers, on 55, 65 and 86-foot lots. Blue Star Land develops it.'),
    'DFW-CH-017': ('3324f9c6',
        'Sells finished lots to production builders such as Highland, Perry and Tradition. Develops Meraki, Sherley Farms and Mirabella.'),
    'DFW-BTR-004': ('035d3027',
        'HHS Residential built its Viridian homes in Arlington. A Blackstone real estate portfolio company.'),
    'DFW-CH-012': ('1f84d9ff',
        'Johnson Development sells lots to its builders, from Cadence townhomes to Del Webb for buyers 55 and over.'),
    'DFW-CH-010': ('1c37fcb6',
        'Hillwood sells lots to eight production builders, including Bloomfield, Beazer, Highland and Tri Pointe.'),
    'DFW-CH-005': ('b644e669',
        "Republic Property Group sells lots to roster builders, David Weekley's Walsh Classic among them. Buildout around 2050."),
    'DFW-CH-013': ('b405ba3d',
        'Sells lots to production builders, Shaddock Caldwell custom homes and Grenadier villas and townhomes. Tellus Group bought it in 2018.'),
    'DFW-002': ('0acaf130',
        "Built the 100-home Wolf Ranch with ICON. Sells one Everything's Included plan library across DFW."),
}


def _h(s):
    return hashlib.sha1((s or "").encode("utf-8")).hexdigest()[:8]


def final(data, market):
    """Replace each screen line, then set each card's type. Returns problems."""
    bad = []
    for t in data["targets"]:
        if t.get("group") == "out":
            continue
        tid = t["target_id"]
        if tid not in SCREEN:
            bad.append("%s has no fact-form screen line" % tid)
            continue
        was, new = SCREEN[tid]
        if _h(t.get("mvp_screen")) != was:
            bad.append("%s: the screen line changed upstream; rewrite its audit13 entry" % tid)
            continue
        t["mvp_screen"] = new
    firm_types.apply(data, market)
    return bad
