# -*- coding: utf-8 -*-
"""Remaining tier B records (medium depth) and the screened-out tail (thin)."""

from data_b import P, PJ, S, C

MID = [
{
 "target_id": "HOU-021", "entity_name": "The Dinerstein Companies", "entity_type": "btr_developer", "entity_role": "vertical_buyer",
 "categories": ["build_to_rent", "multifamily"], "region": "Houston HQ / Fort Bend",
 "homepage_url": "https://www.dinersteincos.com/",
 "synopsis": "Houston multifamily and build-to-rent developer founded in 1955 with more than 80,000 apartments and 50,000 student beds delivered across 26 states. Won the IMN Build-to-Rent Deal of the Year on December 2, 2024 for the 186-home Inspire Homes Missouri City community on 35.29 acres in Fort Bend County, financed with Harrison Street.",
 "key_stat": "186 BTR homes, Harrison Street JV",
 "principals": P(("Brian Dinerstein", "Chief Executive Officer"), ("Jack Dinerstein", "Executive Chairman"),
                 ("Brad Dinerstein", "Managing Partner of Development and Design"), ("John Caltagirone", "President and Partner")),
 "key_projects": PJ(
   ("Inspire Homes Missouri City", "Fort Bend County. 186 single-family build-to-rent homes on 35.29 acres, units 1,172 to 1,442 square feet. IMN Build-to-Rent Deal of the Year, December 2, 2024. Institutional partner Harrison Street.",
    "repeatable", "186 near-identical detached rental units on one site with named institutional capital behind them. Unit sizes are tight and consistent, which is the condition printing rewards.",
    "https://www.dinersteincos.com/press/inspire-homes-missouri-city-receives-national-recognition")),
 "capital_signals": C(("Institutional partnership with Harrison Street on Inspire Homes Missouri City, award announced December 2, 2024", "2024-12-02",
                       "https://www.dinersteincos.com/press/inspire-homes-missouri-city-receives-national-recognition")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 3},
 "mvp_screen": "Good product fit with named institutional capital and a seventy-year Houston operating history. Innovation appetite is the failure: launch coverage of the Inspire brand covers positioning, amenities and unit counts only, and the one available executive quote concerns market fundamentals rather than method.",
 "sources": S(("https://www.dinersteincos.com/press/inspire-homes-missouri-city-receives-national-recognition", "2024-12-02"),
              ("https://www.multifamilyexecutive.com/design-development/construction/the-dinerstein-cos-launches-build-to-rent-brand-inspire-homes_s", "2023-01-13")),
 "audit_flags": ["No dollar figure disclosed for the Harrison Street partnership.", "No construction-method statement located."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-022", "entity_name": "CastleRock Communities", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Houston HQ / Fort Bend",
 "homepage_url": "https://www.c-rock.com/",
 "synopsis": "Privately held homebuilder founded April 1, 2004 in Houston with more than 20,000 homes built across 300-plus communities and a 2020 milestone of over 1,600 closings in a single year. Ranked 49th on the 2025 USA Top Builders list. Daiwa House of Japan acquired an interest in 2021, funding expansion into Arizona, Tennessee and Alabama. Builder in Austin Point Phase I.",
 "key_stat": "20,000+ homes, 300+ communities",
 "principals": P(("Lance Wright", "Chief Executive Officer and Founding Partner"), ("Kirk Breitenwischer", "Senior Executive Vice President")),
 "key_projects": PJ(
   ("Austin Point Phase I", "Rosenberg, Fort Bend County. Named builder in the Signorelli masterplan announced September 22, 2023.",
    "repeatable", "Volume position inside the largest forward lot pipeline in Greater Houston.",
    "https://shoppingcenterbusiness.com/signorelli-co-announces-phase-i-of-4700-acre-master-planned-development-near-houston/"),
   ("Houston production programme", "More than 20,000 homes since 2004 across 300-plus communities, with Houston as the founding market.",
    "repeatable", "Repeat detached production with decision-making in Houston and a foreign strategic owner funding expansion.",
    "https://www.c-rock.com/about")),
 "capital_signals": C(("Daiwa House of Japan acquired an interest in 2021, cited as the funding source for expansion into Arizona in 2023, Tennessee in 2024 and Alabama in 2025. Deal size not disclosed.", "2021-01-01", "https://www.c-rock.com/about")),
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Product fit is strong and a Japanese strategic owner is a capital structure that sometimes carries a method track record with it, since Daiwa House is itself an industrialised-construction company. That connection is a hypothesis worth testing, not evidence. CastleRock publishes no method or technology statement, so the count reflects an absent record rather than a finding against the firm.",
 "sources": S(("https://www.c-rock.com/about", "2026-09-11"),
              ("https://shoppingcenterbusiness.com/signorelli-co-announces-phase-i-of-4700-acre-master-planned-development-near-houston/", "2023-09-22")),
 "audit_flags": ["CastleRock publishes no construction-method or technology content. The count reflects an absent record.",
                 "Daiwa House is a major industrialised-construction company in Japan. Whether that appetite reaches CastleRock is untested and should be checked before the score is trusted.",
                 "Daiwa House deal size not disclosed."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-023", "entity_name": "David Weekley Homes", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Houston HQ, Harris County",
 "homepage_url": "https://www.davidweekleyhomes.com/",
 "synopsis": "Privately held homebuilder founded in Houston in 1976, marking 50 years on March 10, 2026, operating in 19 markets with more than 125,000 homes sold. Builder in Austin Point, Sienna and other Houston master-planned communities.",
 "key_stat": "125,000+ homes, 19 markets, Houston HQ",
 "principals": P(("Jay Brown", "Chief Executive Officer"), ("Chris Weekley", "President and Vice Chairman"),
                 ("David Weekley", "Chairman and Founder")),
 "key_projects": PJ(
   ("Houston master-planned community programme", "Builder role across Austin Point, Sienna and other Houston-area masterplans. More than 125,000 homes sold across 19 markets.",
    "repeatable", "Fifty years of repeat detached production headquartered inside the target geography.",
    "https://houstonagentmagazine.com/2026/03/10/david-weekley-homes-celebrates-50-years/")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Excellent product fit and a Houston head office. No innovation-appetite evidence was found. The firm's 2026 supplier recognition covers standard insulation, waterproofing and fire-stopping installation services with no reference to envelope performance or wall-system method. Privately held, so no disclosed capital figures.",
 "sources": S(("https://houstonagentmagazine.com/2026/03/10/david-weekley-homes-celebrates-50-years/", "2026-03-10"),
              ("https://www.stocktitan.net/news/IBP/ibp-recognized-by-david-weekley-homes-as-2026-national-preferred-umuhb1xfn66z.html", "2026-01-01")),
 "audit_flags": ["No construction-method or technology statement located.", "No Houston community unit counts sourced."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-024", "entity_name": "Ashton Woods Homes", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Alpharetta HQ / Harris, Fort Bend",
 "homepage_url": "https://www.ashtonwoods.com/",
 "synopsis": "Privately held national homebuilder founded in Houston, now headquartered in Alpharetta, Georgia. Lists 14 or more named Houston-area communities including Austin Point, Sunterra Lakes, Spring Creek Trails, Katy Lakes and Westland Ranch. Named builder in Austin Point Phase I.",
 "key_stat": "14+ named Houston communities",
 "principals": P(("Ken Balogh", "President and Chief Executive Officer"), ("Lindsay Motley", "Regional President, Texas"),
                 ("Ryan Lewis", "Chief Operating Officer")),
 "key_projects": PJ(
   ("Houston community roster", "14 or more named Houston-area communities including Austin Point, Sunterra Lakes, Spring Creek Trails, Katy Lakes, Emory Glen and Westland Ranch.",
    "repeatable", "Concurrent positions across a dozen-plus Houston-area masterplans, with a named Texas regional president.",
    "https://www.ashtonwoods.com/houston")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Product fit and Houston breadth both hold, and a Texas regional president is a reachable decision layer. Ashton Woods publishes no construction-method or technology statement.",
 "sources": S(("https://www.ashtonwoods.com/houston", "2026-09-11"),
              ("https://shoppingcenterbusiness.com/signorelli-co-announces-phase-i-of-4700-acre-master-planned-development-near-houston/", "2023-09-22")),
 "audit_flags": ["No firm-specific innovation content found.", "Community-level unit counts not sourced.", "No capital signal with a figure."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-025", "entity_name": "Taylor Morrison Home Corporation", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "build_to_rent", "public"], "region": "Scottsdale HQ / Harris County",
 "homepage_url": "https://www.taylormorrison.com/",
 "synopsis": "NYSE-listed production homebuilder with a Houston division running three brands. Entered Houston build-to-rent through Christopher Todd Communities at Cypress, 240 homes off the Grand Parkway at West Road, leasing from late 2023, and operates the Yardly build-to-rent brand launched November 2022.",
 "key_stat": "240-home Houston BTR community",
 "principals": P(("Darin Rowe", "National President, Build-to-Rent"), ("Amy Rino", "Division President, Houston")),
 "key_projects": PJ(
   ("Christopher Todd Communities at Cypress", "Houston, Harris County. 240 homes adjacent to Avalon at Cypress, leasing from late 2023, built in partnership with Christopher Todd Communities.",
    "repeatable", "240 detached rental units on one site, delivered through a partnership structure the firm built specifically for this format.",
    "https://www.houstonchronicle.com/business/real-estate/article/Taylor-Morrison-starts-first-build-to-rent-16757127.php")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 1, "capital_access": 3},
 "mvp_screen": "A listed builder with a dedicated build-to-rent platform and a named Houston division president. Innovation appetite is thin: a two-year Yardly retrospective references quality, consistency across markets and input costs, with no specifics on method, technology or building systems. Amy Rino's Houston division role dates to a January 2018 appointment and was not reconfirmed for 2026.",
 "sources": S(("https://www.houstonchronicle.com/business/real-estate/article/Taylor-Morrison-starts-first-build-to-rent-16757127.php", "2023-01-01"),
              ("https://www.builderonline.com/land/development/two-years-of-yardly-how-taylor-morrisons-build-to-rent-brand-has-evolved_o", None)),
 "audit_flags": ["Amy Rino's Houston division president role sourced to a January 26, 2018 appointment and not reconfirmed. Verify before outreach.",
                 "Yardly retrospective article carries no confirmed publication date."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-026", "entity_name": "Christopher Todd Communities", "entity_type": "btr_developer", "entity_role": "vertical_buyer",
 "categories": ["build_to_rent"], "region": "Mesa HQ / Montgomery, Harris",
 "homepage_url": "https://www.christophertodd.com/",
 "synopsis": "Arizona build-to-rent operator that made its first Texas acquisition on October 17, 2024, buying the 314-home, 40-acre Cottage Green in Conroe, Montgomery County, rebranded Cottage Living. Also built the 240-home Christopher Todd Communities at Cypress with Taylor Morrison.",
 "key_stat": "314 homes Conroe, 240 homes Cypress",
 "principals": P(("Todd Wood", "Chief Executive Officer and Founder"), ("Brent Long", "President, Christopher Todd Capital")),
 "key_projects": PJ(
   ("Cottage Living, Conroe", "Montgomery County. 314 homes on 40 acres, acquired October 17, 2024. Property manager Willow Bridge.",
    "repeatable", "314 single-storey rental units on one site. The CEO states the strategy through 2025 is to secure sites for the firm's own development rather than acquire.",
    "https://www.christophertodd.com/press-releases/christopher-todd-capital-makes-first-texas-btr-acquisition/"),
   ("Technology package", "Introduced November 20, 2017 across its rental homes: smart-home integration, keyless entry, doorbell camera, thermostat control and gigabit internet.",
    "schedule", "The firm's stated innovation is in the product's fittings, not its structure. No wall-system, framing or structural method was disclosed for Christopher Todd or its builder.",
    "https://www.christophertodd.com/press-releases/christopher-todd-communities-introduces-unrivaled-technology-package-in-rental-living/")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 1, "capital_access": 2},
 "mvp_screen": "Single-storey detached rental is a strong wall-share fit and the stated pivot to self-development means method decisions move in-house. Innovation appetite is thin and specifically consumer-facing. The Conroe purchase price was not disclosed, so capital capacity is inferred from transaction size alone.",
 "sources": S(("https://www.christophertodd.com/press-releases/christopher-todd-capital-makes-first-texas-btr-acquisition/", "2024-10-17"),
              ("https://www.christophertodd.com/press-releases/christopher-todd-communities-introduces-unrivaled-technology-package-in-rental-living/", "2017-11-20")),
 "audit_flags": ["Conroe acquisition price not disclosed.", "Cottage Living was acquired, not developed. Confirm forward self-development pipeline."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-027", "entity_name": "Greystar (Summerwell)", "entity_type": "btr_developer", "entity_role": "vertical_buyer",
 "categories": ["build_to_rent", "multifamily"], "region": "Charleston HQ / Katy, Harris-Waller",
 "homepage_url": "https://www.greystar.com/",
 "synopsis": "National multifamily developer and operator. Broke ground on Summerwell Sunterra, its first Houston-area build-for-rent community, 156 detached homes and townhomes inside the 2,303-acre Sunterra masterplan in Katy, announced October 6, 2023. The Summerwell brand spans more than 10,000 homes across 50 properties nationally.",
 "key_stat": "Summerwell: 10,000+ homes, 50 properties",
 "principals": P(("Bob Faith", "Founder, Chairman and Chief Executive Officer"),
                 ("Brian Herwald", "Managing Director of Development, Houston")),
 "key_projects": PJ(
   ("Summerwell Sunterra", "Katy, Harris and Waller counties. 156 detached homes and townhomes, three and four bedroom, inside Land Tejas's Sunterra masterplan. Announced October 6, 2023.",
    "repeatable", "156 units on one site inside the region's top-selling masterplan, and the first of a national brand with 10,000-plus homes behind it.",
    "https://www.multifamilydive.com/news/greystar-build-to-rent-houston-sunterra-master-plan/695834/")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 3},
 "mvp_screen": "A national platform with a Houston-based managing director of development and a repeatable branded rental format. No innovation-appetite evidence: coverage of Summerwell Sunterra discusses unit count and amenities only, and pricing was explicitly withheld. Deal and construction costs undisclosed.",
 "sources": S(("https://www.multifamilydive.com/news/greystar-build-to-rent-houston-sunterra-master-plan/695834/", "2023-10-06"),
              ("https://therealdeal.com/texas/houston/2023/09/27/greystar-starts-its-first-built-to-rent-community-in-houston-metro/", "2023-09-27")),
 "audit_flags": ["Construction cost and pricing withheld in sourced coverage.", "No innovation-appetite evidence located."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-028", "entity_name": "Sueba USA Corporation", "entity_type": "multifamily_developer", "entity_role": "vertical_buyer",
 "categories": ["multifamily", "developers"], "region": "Houston HQ / Fort Bend",
 "homepage_url": "https://suebausa.com/",
 "synopsis": "Houston multifamily developer active since 1984. Broke ground in 2025 on a 346-unit project at Fort Bend Town Center in Missouri City, master-developed by NewQuest Properties, with completion targeted autumn 2026. Sueba affiliates served as both architect and general contractor.",
 "key_stat": "346 units, in-house architect and GC",
 "principals": P(("Klaus Keller", "President and Chief Executive Officer"), ("John Chiang", "Executive Vice President and Chief Operating Officer"),
                 ("Raymond Gabriele", "Vice President, Development")),
 "key_projects": PJ(
   ("Missouri City 1 at Fort Bend Town Center", "Missouri City, Fort Bend County. 346 units from studio to three bedroom, 496 to 2,088 square feet. Groundbreaking 2025, completion targeted autumn 2026. Master developer NewQuest Properties.",
    "repeatable", "346 units on one site. Sueba affiliates act as architect and general contractor, so design and construction method are decided inside one company.",
    "https://rebusinessonline.com/sueba-usa-breaks-ground-on-346-unit-multifamily-project-in-missouri-city-texas/")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 2, "innovation": 2, "capital_access": 1},
 "mvp_screen": "The structural advantage here is organisational. Sueba designs and builds in-house, which removes the architect and general contractor veto that kills most method changes at other firms. Innovation appetite is scored on that vertical integration rather than on any specific non-standard precedent, which was not found. No capital figures disclosed, which is the main weakness.",
 "sources": S(("https://rebusinessonline.com/sueba-usa-breaks-ground-on-346-unit-multifamily-project-in-missouri-city-texas/", "2026-09-11"),
              ("https://suebausa.com/about-us/", "2026-09-11")),
 "audit_flags": ["No specific offsite, modular or panelized precedent found. Innovation score rests on vertical integration as a structural argument.",
                 "No project cost or financing figure.", "A LinkedIn URL for Klaus Keller appeared in search results but was not opened and is not stored."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-029", "entity_name": "The Hanover Company", "entity_type": "multifamily_developer", "entity_role": "vertical_buyer",
 "categories": ["multifamily", "developers"], "region": "Houston HQ, Harris County",
 "homepage_url": "https://www.hanoverco.com/",
 "synopsis": "Multifamily and industrial developer founded in Houston in 1982, operating across 19 residential markets with in-house development, construction and property management.",
 "key_stat": "19 markets, in-house construction arm",
 "principals": P(("Brandt Bowden", "Chief Executive Officer"), ("Murry Bowden", "Founder and Executive Chairman"),
                 ("John Nash", "President"), ("John Garibaldi", "President, Multifamily")),
 "key_projects": PJ(
   ("National multifamily platform", "Development across 19 residential markets with an in-house construction organisation, headquartered in Houston since 1982.",
    "repeatable", "An in-house construction arm means the builder and the developer are the same decision-maker. Houston headquarters keeps that decision local.",
    "https://www.hanoverco.com/about/")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Vertical integration and a Houston head office are the case. The evidence behind it is weak: despite a full leadership roster being available, no Houston-specific project with an address, unit count, size or date was obtained, and no innovation-appetite evidence was found. Scored on platform characteristics rather than on a sourced Houston position.",
 "sources": S(("https://www.hanoverco.com/about/", "2026-09-11"), ("https://www.hanoverco.com/leadership/", "2026-09-11")),
 "audit_flags": ["No Houston-specific project sourced. Repeatability inferred from platform scale, not from a named local position.",
                 "No capital signal with a figure.", "No innovation-appetite evidence."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-030", "entity_name": "Fidelis Realty Partners", "entity_type": "retail_developer", "entity_role": "vertical_buyer",
 "categories": ["retail", "developers"], "region": "Houston HQ / Brazoria, Montgomery",
 "homepage_url": "https://www.frpltd.com/",
 "synopsis": "Houston retail developer managing roughly 26 million square feet across nearly 100 properties in 12 states. Bought acreage near the Grand Parkway in Alvin, Brazoria County in November 2024 for a planned 280,000 square foot Alvin Marketplace, and separately acquired 33 acres in New Caney, Montgomery County.",
 "key_stat": "26M sf, ~100 properties, 12 states",
 "principals": P(("K. Alan Hassenflu", "Chairman and Chief Executive Officer"), ("Glenn Airola", "Co-President and Chief Operating Officer")),
 "key_projects": PJ(
   ("Alvin Marketplace", "Alvin, Brazoria County. Planned 280,000 square foot retail centre near a future Grand Parkway segment. Land acquired November 2024.",
    "repeatable", "A repeated retail centre format placed in a target county, with a second land position at New Caney acquired inside the same window.",
    "https://therealdeal.com/texas/houston/2024/11/18/fidelis-realty-buys-acreage-for-shopping-center-near-houston/")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Active pipeline in two target counties acquired within 24 months and a repeated format across roughly 100 properties. Two qualifications: retail shells compete against tilt-wall concrete rather than stick framing, and purchase prices are undisclosed in every source checked, so acreage is the only quantified signal. Glenn Airola's title comes from a third-party platform, not a Fidelis page.",
 "sources": S(("https://therealdeal.com/texas/houston/2024/11/18/fidelis-realty-buys-acreage-for-shopping-center-near-houston/", "2024-11-18"),
              ("https://www.frpltd.com/", "2026-09-11")),
 "audit_flags": ["Glenn Airola's title sourced from a third-party CRE platform, not a Fidelis team page. Unverified.",
                 "Headquarters street address not confirmed on frpltd.com.", "All purchase prices undisclosed."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-031", "entity_name": "Read King", "entity_type": "retail_developer", "entity_role": "vertical_buyer",
 "categories": ["retail", "small_commercial", "developers"], "region": "Houston HQ / Fort Bend, Harris",
 "homepage_url": "https://read-king.com/",
 "synopsis": "Houston commercial developer with more than 30 years of activity, having delivered over 3.5 million square feet of Class A retail, more than 30 medical office facilities and 36 freestanding emergency centres, plus more than 100 build-to-suit projects for national retail, restaurant and fitness brands.",
 "key_stat": "36 freestanding ER centres, 100+ build-to-suit",
 "principals": P(("Jeff Read", "Principal and Co-Founder"), ("Ewing King", "Principal"),
                 ("Blake Allen", "Chief Financial Officer"), ("Telisia Amaning", "Chief Operating Officer")),
 "key_projects": PJ(
   ("Freestanding emergency centre programme", "36 freestanding emergency centres delivered, alongside more than 100 build-to-suit projects for national brands.",
    "repeatable", "The most repeated small-commercial building type screened. A freestanding pad building is single-storey and wall-dominant, and 36 near-identical instances is a genuine mobilisation case.",
    "https://read-king.com/about"),
   ("Cross Creek Ranch retail", "Fulshear, Fort Bend County. Office-condominium and retail format within a master-planned community.",
    "repeatable", "Small-commercial product placed inside masterplans that are themselves generating residential volume.",
    "https://read-king.com/about")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 1},
 "mvp_screen": "An under-obvious fit. Small-commercial pad buildings repeated 36 times score as well on the first two screens as any residential builder here, and this is the segment the job posting names that nobody else on the roster serves at volume. Innovation appetite is unevidenced and no capital figure of any kind was found, which is what holds it in tier two.",
 "sources": S(("https://read-king.com/about", "2026-09-11")),
 "audit_flags": ["No capital signal with a figure.", "Individual project square footages and dates not itemised.",
                 "No innovation-appetite evidence located."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-032", "entity_name": "Urban Living", "entity_type": "developer", "entity_role": "vertical_buyer",
 "categories": ["developers", "infill"], "region": "Inner-loop Houston, Harris County",
 "homepage_url": "https://urbanliving.com/",
 "synopsis": "Houston developer and brokerage of inner-loop townhome communities, active for decades across the Washington Corridor, Montrose and adjacent neighbourhoods.",
 "key_stat": "Inner-loop attached townhome production",
 "principals": P(("Vinod Ramani", "Owner")),
 "key_projects": PJ(
   ("Inner-loop townhome communities", "Multiple attached three-storey townhome communities across inner Houston.",
    "repeatable", "Attached three-storey townhomes are the highest wall-share residential type available, and this is a repeat production model rather than a one-off.",
    "https://urbanliving.com/developments.php")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 1},
 "mvp_screen": "Product type is close to ideal and the model is repeat production. Everything else is thin. No community names, unit counts or capital figures were obtained, and the only ownership attribution comes from a third-party contact database rather than a company page. Verify the principal before any approach.",
 "sources": S(("https://urbanliving.com/developments.php", "2026-09-11")),
 "audit_flags": ["The firm's own site publishes no leadership and refuses automated retrieval. The owner is held on an indexed LinkedIn headline naming him with the firm, and on nothing else.",
                 "No named communities, unit counts or capital figures.", "No innovation-appetite evidence."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-033", "entity_name": "Coventry Homes", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Houston HQ, Harris County",
 "homepage_url": "https://www.coventryhomes.com/",
 "synopsis": "Houston-founded production homebuilder established 1988, now a subsidiary of NASDAQ-listed Dream Finders Homes. Operates close to 100 unique communities across four Texas markets with more than 55,000 homes closed company-wide. Active builder in Sienna.",
 "key_stat": "~100 communities, 55,000+ homes closed",
 "principals": [],
 "key_projects": PJ(
   ("Texas community programme", "Close to 100 unique communities across Houston, Dallas-Fort Worth, Austin and San Antonio, including a builder role at Sienna.",
    "repeatable", "Repeat detached production with Houston origins, now backed by a listed parent.",
    "https://www.coventryhomes.com/about-us/")),
 "capital_signals": C(("Owned by NASDAQ-listed Dream Finders Homes, which announced the purchase of parent McGuyer Homebuilders (MHI, doing business as Coventry Homes) on 13 September 2021 for $150 million in preferred stock.", None, "https://investors.dreamfindershomes.com/news-events/press-releases/detail/13/dream-finders-homes-to-acquire-the-assets-of-mcguyer")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Product fit holds and a listed parent supplies capital. No named Coventry executive was found on any retrieved page, which is a real access problem for a rolodex: there is currently no door. Resolve the parent-subsidiary decision rights before spending time here.",
 "sources": S(("https://www.coventryhomes.com/about-us/", "2026-09-11")),
 "audit_flags": ["Decision rights between parent and subsidiary not published.",
                 "No Houston community unit counts."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-034", "entity_name": "Brightland Homes", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Addison HQ / Montgomery, Harris",
 "homepage_url": "https://www.brightlandhomes.com/",
 "synopsis": "Production homebuilder founded in 1994 as Gehan Homes, renamed Brightland Homes effective March 21, 2023 across 110 active communities, ranked the thirteenth-largest private United States homebuilder with more than 17,000 homes delivered at the time of the rename. Sumitomo Forestry acquired a stake reported May 1, 2014 and expanded it April 5, 2016. Builder at The Woodlands Hills.",
 "key_stat": "110 communities, 17,000+ homes delivered",
 "principals": [],
 "key_projects": PJ(
   ("Texas community programme", "110 active communities consolidated under the Brightland name in March 2023, including a builder role at The Woodlands Hills in Montgomery County.",
    "repeatable", "Repeat detached production at scale with a Houston-area masterplan position.",
    "https://press.brightlandhomes.com/gehan-homes-announces-name-change-to-brightland-homes")),
 "capital_signals": C(("Sumitomo Forestry America acquired a controlling stake in Gehan Homes, reported May 1, 2014 and expanded April 5, 2016. Deal size not disclosed.", "2014-05-01",
                       "https://www.businesswire.com/news/home/20140501005392/en/Texas-Homebuilder-Gehan-Homes-Sells-Stake-Sumitomo")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Volume and product type fit. The interesting feature is the owner: Sumitomo Forestry is a Japanese timber and industrialised-housing group, which makes the parent a plausible route into a method conversation and equally a plausible structural reason to prefer timber framing. Untested either way. No current chief executive confirmed, which leaves no door.",
 "sources": S(("https://press.brightlandhomes.com/gehan-homes-announces-name-change-to-brightland-homes", "2023-02-21"),
              ("https://www.businesswire.com/news/home/20140501005392/en/Texas-Homebuilder-Gehan-Homes-Sells-Stake-Sumitomo", "2014-05-01")),
 "audit_flags": ["Current chief executive not confirmed. The 2023-era CEO subsequently moved to First America Homes.",
                 "Sumitomo Forestry is a timber group. Owner may favour wood framing structurally. Test this before investing time.",
                 "No Houston-specific community list with unit counts."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-035", "entity_name": "Avenue CDC", "entity_type": "nonprofit_developer", "entity_role": "vertical_buyer",
 "categories": ["civic_institutional", "affordable"], "region": "Near Northside, Harris County",
 "homepage_url": "https://avenuecdc.org/",
 "synopsis": "Nonprofit community development corporation building affordable homes since 1991 and operating in Houston's Near Northside since 2002, with five named developments in the neighbourhood. Received $3.4 million from the City of Houston for its Near Northside Community Resource Center.",
 "key_stat": "5 named Near Northside developments",
 "principals": P(("Mary Lawler", "Chief Executive Officer"), ("Nicole Cassier", "Chief Strategy Officer"),
                 ("Karen Briggs Gwin", "Chief Financial Officer")),
 "key_projects": PJ(
   ("Near Northside development programme", "Five named developments since 2002: Avenue Place, Avenue Terraces, Avenue Station, Avenue Villas and Fulton Gardens.",
    "repeatable", "Five repeat affordable developments in one neighbourhood under one owner.",
    "https://avenuecdc.org/community-development/community-initiatives/"),
   ("Post-Harvey resilience framing", "Avenue CDC's Near Northside work framed by Rice University's Kinder Institute as a test case for equitable transit-oriented development after Hurricane Harvey.",
    "resilience", "Resilience positioning tied to Harvey by an independent academic institution rather than by the developer's own marketing.",
    "https://kinder.rice.edu/urbanedge/harvey-be-turning-point-equitable-transit-oriented-development-houston")),
 "capital_signals": C(("$3.4 million from the City of Houston for the Near Northside Community Resource Center", None,
                       "https://www.virtualbx.com/feature-story/houston-avenue-cdc-receives-3-4m-from-city-for-its-near-northside-community-resource-center/")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 2, "capital_access": 1},
 "mvp_screen": "Affordable low-rise housing is where printed walls have the clearest cost argument, and the post-Harvey resilience framing is real and independently sourced. Capital is the constraint: a $3.4 million municipal grant is the only figure available and it is small relative to a printer mobilisation. Best approached alongside the Houston Housing Authority rather than alone.",
 "sources": S(("https://avenuecdc.org/about-us/board-staff/", "2026-09-11"),
              ("https://avenuecdc.org/community-development/community-initiatives/", "2026-09-11"),
              ("https://kinder.rice.edu/urbanedge/harvey-be-turning-point-equitable-transit-oriented-development-houston", "2026-09-11")),
 "audit_flags": ["No unit counts, addresses or completion dates for any of the five named developments.",
                 "Kinder Institute framing sourced from a headline. Article not opened to confirm exact language.",
                 "Capital capacity is small relative to printer mobilisation economics."],
 "hue_hex": "#C8102E",
},
{
 "target_id": "HOU-036", "entity_name": "Midway", "entity_type": "developer", "entity_role": "vertical_buyer",
 "categories": ["developers", "mixed_use", "infill"], "region": "Houston HQ / East End, Harris County",
 "homepage_url": "https://www.midway.team/",
 "synopsis": "Houston investment and development firm that broke ground on August 26, 2021 on East River, a 150-acre mixed-use redevelopment of the former industrial turning-basin site on Buffalo Bayou, planned at 60 city blocks. Phase One covers 26 acres including The Laura at 360 units, 250,000 square feet of office and 110,000 square feet of retail. Combined with Parkway Property Investments in May 2023.",
 "key_stat": "East River: 150 acres, 60 city blocks",
 "principals": P(("Bradley Freels", "Chairman and Chief Executive Officer"), ("David Hightower", "Executive Vice President"),
                 ("Clark Thompson", "Executive Vice President and General Counsel")),
 "key_projects": PJ(
   ("East River", "100 Jensen Drive, Fifth Ward. 150 acres planned at 60 city blocks over a decades-long horizon. Phase One 26 acres: The Laura at 360 units, 250,000 square feet office, 110,000 square feet retail. Groundbreaking August 26, 2021.",
    "repeatable", "Phased delivery of low- and mid-rise blocks on a single 150-acre site over decades. ",
    "https://rebusinessonline.com/midway-breaks-ground-on-150-acre-east-river-mixed-use-development-in-houston/"),
   ("Port Houston headquarters", "95,000 square foot build-to-suit at East River plus a dedicated parking garage, groundbreaking spring 2024, completion targeted summer 2025.",
    "capital", "Institutional build-to-suit counterparty inside the same masterplan.",
    "https://www.jw.com/news/result-east-river-port-houston-development/")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 2, "innovation": 2, "capital_access": 1},
 "mvp_screen": "Sixty city blocks on one site is a strong structural argument for a method that amortises across repetition, and Midway's district-scale design ambition suggests receptivity. The evidence is weaker than the story: no capital figure for East River was disclosed in any source, the About page returned a 404, and the corporate relationship with Parkway after the May 2023 combination is unresolved. Confirm which entity holds development scope before pitching.",
 "sources": S(("https://rebusinessonline.com/midway-breaks-ground-on-150-acre-east-river-mixed-use-development-in-houston/", "2021-08-26"),
              ("https://www.midway.team/places/east-river", "2026-09-11"),
              ("https://www.prnewswire.com/news-releases/parkway-and-midway-form-preeminent-real-estate-investment-operations-and-management-firm-301820191.html", "2023-05-10")),
 "audit_flags": ["Midway combined with Parkway Property Investments in May 2023. Current brand and entity relationship unresolved. Confirm who holds development scope.",
                 "Midway About page returned 404. Leadership confirmed from secondary sources.",
                 "No capital or financing figure for East River."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-037", "entity_name": "The Deal Company (Sawyer Yards)", "entity_type": "developer", "entity_role": "vertical_buyer",
 "categories": ["developers", "adaptive_reuse"], "region": "Washington Corridor, Harris County",
 "homepage_url": "https://www.dealco.net/",
 "synopsis": "Developer of Sawyer Yards, launched in 2005 with the conversion of a 75,000 square foot warehouse and grown with co-developers Lovett Commercial and Silver Street Capital into a 55-acre campus of 27 buildings, 18 of them historic, holding more than two million square feet and over 600 creative tenants.",
 "key_stat": "55 acres, 27 buildings, 2M+ sf",
 "principals": P(("Jon Deal", "Founder and Chief Executive Officer")),
 "key_projects": PJ(
   ("Sawyer Yards", "Washington Corridor, Houston. 55 acres, 27 buildings including 18 historic, more than two million square feet, launched 2005.",
    "method_risk", "Two decades of converting industrial structures into occupied space. Sustained willingness to build inside awkward existing fabric, repeated 27 times.",
    "https://www.sawyeryards.com/about")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 1, "innovation": 3, "capital_access": 1},
 "mvp_screen": "High method tolerance demonstrated over twenty years, but the wrong product for the tool. Adaptive reuse of existing buildings means little new wall to print, which is why wall share scores low. No capital figures confirmed and the principal's title comes from a third-party database. Worth a conversation for the ground-up phases only.",
 "sources": S(("https://www.sawyeryards.com/about", "2026-09-11")),
 "audit_flags": ["Jon Deal's title sourced from a third-party database, not a company page.",
                 "A possible $100 million district figure exists in an unopened 2013 headline. Verify before use.",
                 "Adaptive reuse means limited new wall area. Product fit is structurally weak."],
 "hue_hex": "#8FA37E",
},
{
 "target_id": "HOU-038", "entity_name": "Cameron Management", "entity_type": "developer", "entity_role": "vertical_buyer",
 "categories": ["developers", "adaptive_reuse"], "region": "Downtown Houston, Harris County",
 "homepage_url": "https://cameronmanagement.com/",
 "synopsis": "Owner of the Niels Esperson and Mellie Esperson towers, built 1927 in downtown Houston, reported in 2023 to be converting up to 100 apartment units into the buildings at a stated $50 million renovation cost.",
 "key_stat": "$50M conversion, up to 100 units",
 "principals": P(("Dougal A. Cameron", "President and Owner"), ("William T. Dom", "Chief Operating Officer")),
 "key_projects": PJ(
   ("Esperson buildings conversion", "Downtown Houston. 1927 towers converted to up to 100 apartments at a stated $50 million renovation cost, first units expected within months as of January 2023.",
    "method_risk", "Paying a premium to work inside a 1927 structural envelope is direct evidence of tolerance for non-standard construction conditions.",
    "https://houston.org/news/downtown-conversions-turn-aging-office-towers-new-residences-hotels/")),
 "capital_signals": C(("$50 million renovation cost for the Esperson residential conversion", "2023-01-01",
                       "https://houston.org/news/downtown-conversions-turn-aging-office-towers-new-residences-hotels/")),
 "scores": {"repeatability": 1, "wall_share": 1, "innovation": 3, "capital_access": 2},
 "mvp_screen": "Fails the first two screens and clears the third emphatically. Interior conversion of an existing high-rise involves almost no new exterior wall, and one building is not a repeatable unit count. Listed because the innovation evidence is genuine and the principal is reachable, so it is a relationship worth having if the firm moves to ground-up work.",
 "sources": S(("https://houston.org/news/downtown-conversions-turn-aging-office-towers-new-residences-hotels/", "2023-01-01"),
              ("https://cameronmanagement.com/contact", "2026-09-11")),
 "audit_flags": ["Unit count stated only as up to 100.", "Product type structurally mismatched to a printed exterior wall system."],
 "hue_hex": "#8FA37E",
},
]

# ------------------------------------------------------------------ THE TAIL
# name, type, role, region, url, one-line reason it screened out, scores, tier-forcing flag
TAIL = [
 ("HOU-039", "Land Tejas", "mpc_developer", "channel", "Houston / Katy, Harris-Waller", "https://landtejas.com/",
  "Develops lots and sells them to builders, so it never buys a wall system. Sunterra's 2,303 acres and 15-builder roster make it the largest single builder roster screened, and Starwood Capital took a majority interest on December 29, 2021.",
  {"repeatability": 3, "wall_share": 0, "innovation": 0, "capital_access": 3},
  "https://www.prnewswire.com/news-releases/starwood-capital-group-acquires-majority-interest-in-houston-based-land-tejas-301451396.html", None),
 ("HOU-040", "Johnson Development Corp", "mpc_developer", "channel", "Houston / Fort Bend, Montgomery", "https://www.johnsondevelopment.com/",
  "Land developer running 14 concurrent Houston-area masterplans including Sienna and Cross Creek West. Channel value is high and direct wall purchasing is nil. Johnson Development publishes no construction-method content.",
  {"repeatability": 3, "wall_share": 0, "innovation": 0, "capital_access": 1},
  "https://www.johnsondevelopment.com/mpc_houston", "Johnson Development publishes no construction-method content. The count reflects an absent record."),
 ("HOU-041", "Caldwell Companies", "mpc_developer", "channel", "Cypress / Montgomery, Harris", "https://caldwellcos.com/",
  "Land developer of Towne Lake and The Highlands, the latter 2,300 acres with 4,000 planned homes and 12 concurrent builders. Sells lots, does not pour walls. Publishes no construction-method content.",
  {"repeatability": 3, "wall_share": 0, "innovation": 0, "capital_access": 1},
  "https://realtynewsreport.com/caldwell-starts-2300-acre-master-planned-community/", "Caldwell publishes no construction-method content."),
 ("HOU-042", "Friendswood Development Company", "mpc_developer", "channel", "Houston / Montgomery, Galveston", "https://friendswooddevelopment.com/",
  "Land developer founded 1962 and a wholly owned Lennar subsidiary since 2000. The channel leads directly to Lennar, which is a vertical builder.",
  {"repeatability": 2, "wall_share": 0, "innovation": 0, "capital_access": 2},
  "https://friendswooddevelopment.com/about-fdc", "No named principals found. Lennar parent relationship is the actual route."),
 ("HOU-043", "Newland Communities", "mpc_developer", "channel", "San Diego HQ / Katy, Harris", "https://newlandco.com/",
  "Land developer of the 3,600-acre Elyson community in Katy. The headquarters location rests on a third-party business listing.",
  {"repeatability": 2, "wall_share": 0, "innovation": 0, "capital_access": 1},
  "https://www.constructiondive.com/news/newland-communities-3600-acre-elyson-development-set-to-open-near-houston/428102/",
  "No principals sourced. Headquarters unconfirmed. Record too thin to action."),
 ("HOU-044", "RSK Real Estate Partners", "btr_developer", "vertical_buyer", "Chicago HQ / Katy, Harris", "https://rskrealestatepartners.com/",
  "Two Katy build-to-rent duplex projects within about a mile of each other, 156 and 210 units. ",
  {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 1},
  "https://www.katyedc.org/news-and-media/news/p/item/63468/chicago-btr-developer-acquires-9-acres-for-duplex-project-in-harris-county", None),
 ("HOU-045", "Chesmar Homes", "homebuilder", "vertical_buyer", "Spring, Harris-Montgomery", "https://www.chesmar.com/",
  "Production builder headquartered in Spring with divisions in three other Texas markets and a builder role at Sienna. Chesmar publishes no Houston community unit counts and no construction-method content.",
  {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 1},
  "https://www.chesmar.com/", "Chesmar publishes no construction-method or technology content. The count reflects an absent record."),
 ("HOU-046", "MetroNational", "developer", "vertical_buyer", "Memorial City, Harris County", "https://www.metronational.com/",
  "Family-owned developer of the Memorial City district and a joint-venture partner on the March 30, 2026 M-K-T Heights acquisition. No ground-up start with figures was located and the leadership hierarchy is contradictory across dated sources.",
  {"repeatability": 2, "wall_share": 1, "innovation": 1, "capital_access": 2},
  "https://natlawreview.com/press-releases/metronational-grows-greater-houston-portfolio-landmark-m-k-t-heights",
  "Jason Johnson and Scooter Hicks both attributed the President title in different dated sources. Hierarchy unresolved."),
 ("HOU-047", "Baker Katz", "retail_developer", "vertical_buyer", "Houston / Harris, Galveston", "https://bakerkatz.com/",
  "Retail developer with more than 80 completed projects, acquiring rather than building in its recent Houston activity. Both 2022 and 2024 transactions were purchases of existing 108,000 square foot centres.",
  {"repeatability": 2, "wall_share": 2, "innovation": 0, "capital_access": 2},
  "https://bakerkatz.com/media-news/108k-sf-retail-center-in-northwest-houston-is-baker-katzs-largest-acquisition-since-2022/", None),
 ("HOU-048", "Wulfe & Co.", "retail_developer", "vertical_buyer", "Post Oak / Harris, Galveston", "https://www.wulfe.com/",
  "Manages and leases more than 7.2 million square feet of Houston retail across at least nine named centres. Current activity is management and leasing rather than ground-up development, and no project figures were obtained.",
  {"repeatability": 2, "wall_share": 2, "innovation": 0, "capital_access": 1},
  "https://www.wulfe.com/aboutwulfe", None),
 ("HOU-049", "StreetLights Residential", "multifamily_developer", "vertical_buyer", "Dallas HQ / Museum District", "https://www.streetlights.com/",
  "Completed The Langley, a 134-unit, 20-storey tower in the Museum District, on July 13, 2026 with Hunt Real Estate. High-rise concrete towers put a small share of cost in wall assembly, which is the wrong end of the product range.",
  {"repeatability": 2, "wall_share": 1, "innovation": 1, "capital_access": 2},
  "https://rejournals.com/the-langley-multifamily-development-opens-in-houston/",
  "A LinkedIn URL for Doug Chesnut surfaced in search results but was not opened and is not stored."),
 ("HOU-050", "The Finger Companies", "multifamily_developer", "vertical_buyer", "Houston, Harris County", "https://www.fingercompanies.com/",
  "Houston multifamily owner-operator. Founder Marvy Finger sold a 20-property portfolio reported at $2 billion before his death in 2023. Current product is high-rise and mid-rise, and no ground-up start was sourced.",
  {"repeatability": 2, "wall_share": 1, "innovation": 0, "capital_access": 2},
  "https://www.houstonchronicle.com/business/real-estate/article/Finger-Cos-sells-20-apartment-properties-to-16546804.php",
  "The $2 billion portfolio sale is sourced from a headline only. Date unconfirmed."),
 ("HOU-051", "Rice Management Company (Ion District)", "institutional", "channel", "Midtown, Harris County", "https://iondistrict.com/",
  "Developing the 16-acre Ion District anchored by the adaptively reused former Sears building, with a roughly 200,000 square foot expansion called The Arc. No leadership names or titles could be sourced from any retrieved page.",
  {"repeatability": 1, "wall_share": 1, "innovation": 2, "capital_access": 2},
  "https://iondistrict.com/about/", "No principals sourced. Searches returned unrelated individuals. No door identified."),
 ("HOU-052", "Medistar Corporation", "developer", "vertical_buyer", "Texas Medical Center, Harris County", "https://www.medistarcorp.com/",
  "Medical and mixed-use developer that closed $550 million in financing on June 24, 2021 for Texas A&M Innovation Plaza with Healthcare Trust of America and CIM Group. Product is high-rise institutional, and the company's own team pages returned only boilerplate.",
  {"repeatability": 1, "wall_share": 1, "innovation": 1, "capital_access": 3},
  "https://finance.yahoo.com/news/medistar-corporation-announces-closing-funding-200500786.html",
  "Company About and Team pages returned only boilerplate. Monzer Hourani's exact current title varies across sources and is unresolved."),
 ("HOU-053", "Wolff Companies", "mpc_developer", "channel", "Waller County / Energy Corridor", "https://wolffcompanies.com/",
  "Land developer of the 587-acre Beacon Hill project on the US-290 corridor in Waller County. Sells land rather than building vertical, and the leadership page lists four names without titles.",
  {"repeatability": 2, "wall_share": 0, "innovation": 0, "capital_access": 1},
  "https://wolffcompanies.com/", "Leadership page lists names without titles. None confirmed. CityCentre ownership status unresolved."),
 ("HOU-054", "StoneLake Capital Partners", "pe_developer", "capital", "Dallas HQ / West Houston", "https://stonelake.com/",
  "Private equity real estate firm that developed a 195,960 square foot Amazon-leased industrial building at West 10 in Houston, acquired July 2020. Big-box industrial is tilt-wall territory with a low wall share of total cost.",
  {"repeatability": 2, "wall_share": 1, "innovation": 0, "capital_access": 2},
  "https://stonelake.com/case-studies/west-10/", None),
 ("HOU-055", "CAF Capital Partners", "pe_developer", "capital", "Frisco HQ / Houston assets", "https://cafcapital.com/",
  "Texas multifamily sponsor citing more than $4 billion in closed transactions. Both identified Houston positions, Arden Cypress Station in July 2022 and Huxley at Medical Center in December 2021, are value-add acquisitions of existing product rather than ground-up development.",
  {"repeatability": 1, "wall_share": 1, "innovation": 0, "capital_access": 2},
  "https://cafcapital.com/about-us", "No ground-up Houston development identified. Acquirer, not a builder."),
 ("HOU-056", "Sarofim Realty Advisors", "institutional", "capital", "Houston HQ, national mandate", "https://sraco.com/",
  "Houston investment manager with $1.2 billion in assets under management per Form ADV data. No named Houston ground-up position could be identified and the firm does not disclose deal-level detail publicly.",
  {"repeatability": 0, "wall_share": 0, "innovation": 0, "capital_access": 2},
  "https://sraco.com/about.html", "No Houston ground-up position identified. Form ADV data obtained via a third-party aggregator, not SEC IAPD."),
 ("HOU-057", "Hartman Income REIT / Silver Star Properties", "reit", "vertical_buyer", "Katy Freeway, Harris County", "https://hartman-properties.com/",
  "Texas commercial operator whose corporate identity is unresolved. Public reporting references a related or successor entity, Silver Star Properties REIT, with a different chief executive. No Houston project was confirmed as a Hartman asset.",
  {"repeatability": 1, "wall_share": 1, "innovation": 0, "capital_access": 1},
  "https://hartman-properties.com/about-hartman-reit/",
  "Corporate relationship between Hartman Income REIT, Hartman Properties, Hartman REIT Management and Silver Star Properties REIT unresolved. Do not approach until clarified."),
]
