# -*- coding: utf-8 -*-
"""Tier A records for the ICON Houston rolodex."""

A_TIER = [
{
 "target_id": "HOU-001",
 "entity_name": "Wan Bridge Group",
 "entity_type": "btr_developer",
 "entity_role": "vertical_buyer",
 "categories": ["build_to_rent", "developers"],
 "region": "Houston HQ / Harris, Fort Bend",
 "homepage_url": "https://wanbridge.com/",
 "synopsis": "Houston-headquartered build-to-rent developer operating since 2016 across Houston, Austin and Dallas. Announced five new Texas build-to-rent projects on March 12, 2025, including Canvas on Founders Hill in Fulshear and Eldridge Tower in Houston. Held five projects under way with five to seven more in the pipeline as of April 10, 2025.",
 "key_stat": "5 TX projects under way, 5-7 in pipeline (Apr 2025)",
 "principals": [
   {"name": "Ting Qiao", "role": "Chief Executive Officer and Co-Founder", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Canvas on Founders Hill", "detail": "Fulshear, Fort Bend County. Announced March 12, 2025.",
    "signal_type": "repeatable", "fit_signal": "One of five concurrent Texas build-to-rent starts announced in a single release. Wan Bridge builds and holds, so schedule and durability accrue to the same balance sheet.",
    "url": "https://www.businesswire.com/news/home/20250312098923/en/Wan-Bridge-Expands-Texas-Footprint-with-Five-New-Projects"},
   {"name": "Eldridge Tower", "detail": "Houston, Harris County. Delivery targeted Q2 2025.",
    "signal_type": "repeatable", "fit_signal": "Second concurrent Houston-market build-to-rent position, confirming repeat volume inside one metro.",
    "url": "https://www.businesswire.com/news/home/20250312098923/en/Wan-Bridge-Expands-Texas-Footprint-with-Five-New-Projects"},
   {"name": "Proprietary construction ERP and site robotics", "detail": "Six-year in-house build. Automates construction budgets, scheduling and inspection reporting. Robotic units run site inspections and upload progress data for AI delay and quality detection.",
    "signal_type": "method_risk", "fit_signal": "The only firm screened with dated, named-executive evidence of sustained premium spend on unproven construction technology. ",
    "url": "https://keycrew.co/journal/wan-bridge-groups-ting-qiao-on-elevating-the-build-to-rent-market/"},
 ],
 "capital_signals": [],
 "quote": {"text": "Real estate is traditionally a low-tech industry, brick and mortar, centuries old. It's essentially a dinosaur industry.",
           "speaker": "Ting Qiao, Chief Executive Officer and Founder", "date": "2026-04-10",
           "url": "https://keycrew.co/journal/wan-bridge-groups-ting-qiao-on-elevating-the-build-to-rent-market/"},
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 3, "capital_access": 2},
 "mvp_screen": "Clears all three. Repeatable low-rise rental product in one metro, wall-heavy detached and attached format, and the only documented appetite in Greater Houston for unproven construction technology. Holds the asset, so the durability argument lands on the owner rather than a departed merchant builder. No disclosed fund or financing figure, which is the one open item.",
 "sources": [
   {"url": "https://www.businesswire.com/news/home/20250312098923/en/Wan-Bridge-Expands-Texas-Footprint-with-Five-New-Projects", "date": "2025-03-12"},
   {"url": "https://keycrew.co/journal/wan-bridge-groups-ting-qiao-on-elevating-the-build-to-rent-market/", "date": "2026-04-10"},
 ],
 "audit_flags": ["No disclosed fund size, financing figure or JV for Wan Bridge. Capital capacity inferred from concurrent project count, not from a stated figure.",
                 "LinkedIn URLs unsourced for both principals. Verify before outreach."],
 "hue_hex": "#FF4F00",
},
{
 "target_id": "HOU-002",
 "entity_name": "Cole Klein Builders / Zuri Gardens",
 "entity_type": "homebuilder",
 "entity_role": "proven_adopter",
 "categories": ["developers", "proven_3dp"],
 "region": "Southeast Houston, Harris County",
 "homepage_url": None,
 "no_web_presence": True,
 "synopsis": "Builder and developer of Zuri Gardens, an 80-home community on 13 acres near Hobby Airport in southeast Houston, built with 3D-printed construction in partnership with Houston construction-technology firm HiveASMBLD and Green Cement of Jewett, Texas. Homes priced roughly $250,000 to $275,000 with completion targeted late 2026.",
 "key_stat": "80 3D-printed homes on 13 acres",
 "principals": [
   {"name": "Cole Klein", "role": "Builder and developer, Zuri Gardens", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Zuri Gardens", "detail": "80 homes on 13 acres, southeast Houston near Hobby Airport. Priced roughly $250,000 to $275,000. Completion targeted late 2026. Printing partner HiveASMBLD; cement partner Green Cement (Jewett, Texas).",
    "signal_type": "method_risk", "fit_signal": "The largest committed 3D-printed residential project in Greater Houston. Eighty near-identical units on one site. HiveASMBLD is printing it.",
    "url": "https://www.houstoniamag.com/home-and-real-estate/2025/12/3d-printed-houses-neighborhood-houston"},
 ],
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 3, "capital_access": 1},
 "mvp_screen": "Clears all three on the product, and is the only Houston entity that has already signed for printed walls at scale. Capital and access score low because no fund, lender or equity partner is disclosed and the firm has no confirmed corporate web presence. Treat as a competitive-displacement conversation, not a greenfield pitch.",
 "sources": [
   {"url": "https://www.houstoniamag.com/home-and-real-estate/2025/12/3d-printed-houses-neighborhood-houston", "date": "2025-12-01"},
   {"url": "https://www.click2houston.com/news/local/2025/11/06/houstons-first-3d-printed-home-community-is-almost-ready-to-rollor-print/", "date": "2025-11-06"},
 ],
 "audit_flags": ["Currently building with HiveASMBLD, a Houston-based competitor. Approach is displacement or second-phase supply, not first contact.",
                 "No corporate homepage confirmed for Cole Klein Builders. Entity structure unverified.",
                 "No capital signal with a figure. Project financing undisclosed."],
 "hue_hex": "#FF4F00",
},
{
 "target_id": "HOU-003",
 "entity_name": "Houston Housing Authority",
 "entity_type": "public_agency",
 "entity_role": "vertical_buyer",
 "categories": ["civic_institutional", "developers"],
 "region": "Third Ward / citywide, Harris County",
 "homepage_url": "https://www.housingauthorityhouston.org/",
 "synopsis": "Public housing agency that announced on October 22, 2025 a five-phase redevelopment of Cuney Homes, Houston's oldest public housing community, opened 1943. The 2025 to 2032 programme is backed by a $50 million HUD Choice Neighborhood Implementation Grant against a total project cost stated at over $600 million. Jamie Bryant was named President and Chief Executive Officer in February 2025.",
 "key_stat": "$600M+ programme, 5 phases, 2025-2032",
 "principals": [
   {"name": "Jamie Bryant", "role": "President and Chief Executive Officer, named February 2025", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Cuney Homes redevelopment", "detail": "Third Ward, Harris County. Five phases, 2025 to 2032. $50 million HUD Choice Neighborhood Implementation Grant against total cost stated above $600 million. Announced October 22, 2025.",
    "signal_type": "repeatable", "fit_signal": "The clearest repeatable-unit case screened: one location, one owner, seven years of phased low-rise delivery. Phase one performance sets the method for every phase after it.",
    "url": "https://communityimpact.com/houston/bellaire-meyerland-west-university/development/2025/10/27/houston-housing-authority-to-redevelop-citys-oldest-public-housing-community-in-7-year-plan/"},
   {"name": "Independence Heights redevelopment", "detail": "Houston. Continuing as of February 2025 following community consultation.",
    "signal_type": "repeatable", "fit_signal": "A second concurrent redevelopment programme under the same agency.",
    "url": "https://www.houstonpublicmedia.org/articles/housing/2025/02/19/514255/houston-housing-authority-to-continue-independence-heights-project-following-community-pushback/"},
 ],
 "capital_signals": [
   {"text": "$50 million HUD Choice Neighborhood Implementation Grant, part of a stated $600 million-plus total project cost", "date": "2025-10-22",
    "url": "https://communityimpact.com/houston/bellaire-meyerland-west-university/development/2025/10/27/houston-housing-authority-to-redevelop-citys-oldest-public-housing-community-in-7-year-plan/"},
 ],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 1, "capital_access": 3},
 "mvp_screen": "Repeatability and wall share are the strongest in the roster and the capital is federal and committed. Innovation appetite is unevidenced, which is the gap. Offsetting it: public procurement is an open door with a published process, and HUD programmes reward cost and schedule performance directly. Federal funding also brings Buy America and procurement rules that must be checked against ICON's supply chain before any bid.",
 "sources": [
   {"url": "https://communityimpact.com/houston/bellaire-meyerland-west-university/development/2025/10/27/houston-housing-authority-to-redevelop-citys-oldest-public-housing-community-in-7-year-plan/", "date": "2025-10-27"},
   {"url": "https://clpha.org/news/2025/houston-housing-authority-names-jamie-bryant-president-ceo", "date": "2025-02-01"},
 ],
 "audit_flags": ["Cuney Homes existing and planned unit counts not disclosed in the sourced article.",
                 "Buy America and federal procurement applicability to a printed wall system not assessed. Confirm before any bid."],
 "hue_hex": "#C8102E",
},
{
 "target_id": "HOU-004",
 "entity_name": "InTown Homes / Lovett Commercial (Frank Liu)",
 "entity_type": "developer",
 "entity_role": "vertical_buyer",
 "categories": ["developers", "infill"],
 "region": "Inner-loop Houston, Harris County",
 "homepage_url": "https://intownhomes.com/",
 "synopsis": "Two entities under common ownership at a shared Polk Street address. InTown Homes builds three-story attached townhomes across inner Houston and has expanded into Dallas, Austin and Fort Worth. Lovett Commercial converted the 500,000 square foot former Barbara Jordan post office into POST Houston with OMA as architect, and co-developed the 55-acre Sawyer Yards campus.",
 "key_stat": "3-story attached townhomes, citywide volume",
 "principals": [
   {"name": "Frank Liu", "role": "Founder, InTown Homes; President, Lovett Commercial", "linkedin_url": None},
   {"name": "David Foor", "role": "Vice President, Acquisitions, Lovett Commercial", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Inner-loop townhome programme", "detail": "Three-story attached townhomes across inner Houston neighbourhoods. Described in Houston Chronicle coverage as the firm behind the city's ubiquitous three-story townhomes.",
    "signal_type": "repeatable", "fit_signal": "Attached three-story townhomes are the highest wall-share residential product type screened. Party walls on both sides, three storeys inside Titan's 27-foot envelope, and the same unit repeated across dozens of sites.",
    "url": "https://www.houstonchronicle.com/business/article/Frank-Liu-s-big-bets-on-urban-living-pay-off-15053303.php"},
   {"name": "POST Houston", "detail": "401 Franklin Street. 500,000 square feet across 16 acres. Adaptive reuse of the former Barbara Jordan post office. Architect OMA.",
    "signal_type": "geometry", "fit_signal": "Commissioning OMA for a structural reuse of this scale is direct evidence the same ownership pays for design that conventional framing makes expensive.",
    "url": "https://lovettcommercial.com/properties/houston/post-houston"},
   {"name": "Upper East River / Bayou 5th", "detail": "Townhome community within the East River district, Houston.",
    "signal_type": "repeatable", "fit_signal": "Townhome volume placed inside a district-scale masterplan, which concentrates units on one site.",
    "url": "https://www.intownhomes.com/Bayou-5th"},
 ],
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 2, "capital_access": 2},
 "mvp_screen": "Clears all three. The townhome programme is the best wall-share fit in Greater Houston and the volume is genuinely repeatable. Innovation appetite is evidenced on the commercial side rather than the residential side, so the OMA and POST Houston record supports the argument without proving it for the townhome line. No disclosed capital figures.",
 "sources": [
   {"url": "https://lovettcommercial.com/properties/houston/post-houston", "date": "2026-09-11"},
   {"url": "https://www.houstonchronicle.com/business/article/Frank-Liu-s-big-bets-on-urban-living-pay-off-15053303.php", "date": "2026-09-11"},
 ],
 "audit_flags": ["InTown Homes, Lovett Commercial and Lovett Homes may be distinct legal entities under common ownership. Structure not disambiguated.",
                 "No unit counts or capital figures sourced for the townhome programme.",
                 "Frank Liu's exact title at each entity not confirmed on a company page."],
 "hue_hex": "#FF4F00",
},
{
 "target_id": "HOU-005",
 "entity_name": "Radom Capital",
 "entity_type": "developer",
 "entity_role": "vertical_buyer",
 "categories": ["developers", "infill", "mixed_use"],
 "region": "Heights / Montrose, Harris County",
 "homepage_url": "https://www.radomcapital.com/",
 "synopsis": "Houston mixed-use developer that broke ground on the 218-unit Clock Tower Residences in the Heights on August 15, 2025, its fifteenth neighbourhood project there. Previously developed Montrose Collective, a 150,000 square foot mixed-use building designed by Michael Hsu Office of Architecture, financed with $104.75 million closed March 3, 2020 from Bank OZK with J.P. Morgan Asset Management-advised equity.",
 "key_stat": "$104.75M Montrose Collective financing",
 "principals": [
   {"name": "Steve Radom", "role": "Managing Principal", "linkedin_url": None},
   {"name": "Barton Kelly", "role": "Principal", "linkedin_url": None},
   {"name": "Evan Peterson", "role": "Principal", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Montrose Collective", "detail": "Montrose Boulevard at Westheimer. 150,000 square feet with retail frontage on four streets, plus a 10,000 square foot public library. Architect Michael Hsu Office of Architecture. Financing closed March 3, 2020, completed late 2021.",
    "signal_type": "geometry", "fit_signal": "Retail frontage on four streets with a stacked mixed programme is a massing conventional framing prices badly. Commissioning Michael Hsu is evidence of paying a design premium.",
    "url": "https://realtynewsreport.com/radom-capital-receives-104-75m-in-financing-for-montrose-mixed-use-project/"},
   {"name": "Clock Tower Residences", "detail": "1894 Heights clock tower building. 218 units plus four live-work. Groundbreaking August 15, 2025, completion targeted 2027. Construction loan from Veritex Community Bank, four-year term, arranged by JLL Capital Markets.",
    "signal_type": "repeatable", "fit_signal": "218 units on one site alongside an 1894 masonry structure. Both a mobilisation-scale unit count and a second instance of building around non-standard existing fabric.",
    "url": "https://communityimpact.com/houston/heights-river-oaks-montrose/development/2025/08/15/clock-tower-residences-in-the-heights-breaks-ground-as-new-multifamily-development-by-radom-capital/"},
   {"name": "Heights Mercantile", "detail": "Houston Heights retail and restaurant district.",
    "signal_type": "repeatable", "fit_signal": "One of roughly 28 listed projects at similar low-rise mixed-use scale in a concentrated geography.",
    "url": "https://www.radomcapital.com/projects"},
 ],
 "capital_signals": [
   {"text": "$104.75 million construction financing, Bank OZK as lender with J.P. Morgan Asset Management-advised equity, closed March 3, 2020", "date": "2020-03-03",
    "url": "https://realtynewsreport.com/radom-capital-receives-104-75m-in-financing-for-montrose-mixed-use-project/"},
   {"text": "Construction loan from Veritex Community Bank, four-year term, arranged by JLL Capital Markets, for Clock Tower Residences", "date": "2025-08-21",
    "url": "https://therealdeal.com/texas/houston/2025/08/21/radom-capital-asana-partners-secure-houston-multifamily-loan/"},
 ],
 "scores": {"repeatability": 2, "wall_share": 2, "innovation": 3, "capital_access": 3},
 "mvp_screen": "Strongest documented design-premium appetite in the roster paired with named institutional capital and a reachable single-name principal. Repeatability is concentrated rather than deep, fifteen projects in one district rather than hundreds of identical units, and the mixed-use massing means walls carry less of total cost than in detached rental product. Both partials, neither disqualifying.",
 "sources": [
   {"url": "https://realtynewsreport.com/radom-capital-receives-104-75m-in-financing-for-montrose-mixed-use-project/", "date": "2020-03-03"},
   {"url": "https://communityimpact.com/houston/heights-river-oaks-montrose/development/2025/08/15/clock-tower-residences-in-the-heights-breaks-ground-as-new-multifamily-development-by-radom-capital/", "date": "2025-08-15"},
   {"url": "https://natlawreview.com/press-releases/metronational-grows-greater-houston-portfolio-landmark-m-k-t-heights", "date": "2026-03-30"},
 ],
 "audit_flags": ["Unit counts and square footage not obtained for Heights Mercantile.",
                 "LinkedIn URLs unsourced for all principals."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-006",
 "entity_name": "Triten Real Estate Partners",
 "entity_type": "developer",
 "entity_role": "vertical_buyer",
 "categories": ["developers", "infill", "mixed_use"],
 "region": "East End / Fort Bend, Harris County",
 "homepage_url": "https://www.tritenre.com/",
 "synopsis": "Houston vertically integrated investor-developer. Began construction in 2022 on The Mill at 2219 Canal Street, a six-acre East End project combining 75,000 square feet of office, 25,000 square feet of retail and 340 apartments around a preserved 1890s brick lumber mill, framed in cross-laminated timber. Has the 294-unit Landing at Aliana under way in Fort Bend County, opening summer 2027.",
 "key_stat": "340 units, mass timber frame",
 "principals": [
   {"name": "Scott Arnoldy", "role": "Chief Executive Officer, Founder", "linkedin_url": None},
   {"name": "Larry Sloan", "role": "Partner, Chief Development Officer", "linkedin_url": None},
   {"name": "Brent Ozenbaugh", "role": "Partner, Chief Operating Officer", "linkedin_url": None},
   {"name": "Carter Bechtol", "role": "Partner, Head of Triten Residential", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "The Mill", "detail": "2219 Canal Street, East End Houston. Six acres. 75,000 square feet office, 25,000 square feet retail, 340 apartments, around a preserved 14,000 square foot 1890s brick lumber mill. Cross-laminated timber structural frame.",
    "signal_type": "method_risk", "fit_signal": "Triten describes mass timber as a relatively rare alternative to steel and concrete. Specifying and financing a CLT frame is the one documented case in Houston of a developer paying for an unproven structural system.",
    "url": "https://tritenre.com/news/this-historic-reuse-project-shows-the-latest-ways-timber-and-offices-are-changing-industrial-areas"},
   {"name": "The Landing at Aliana", "detail": "Fort Bend County. 294 units. Opening summer 2027.",
    "signal_type": "repeatable", "fit_signal": "294 units of low-rise garden or wrap multifamily on one site, delivering into the same window as Titan's first shipments.",
    "url": "https://www.tritenre.com/about"},
   {"name": "M-K-T Heights", "detail": "600 North Shepherd Drive. 218,000 square foot mixed-use, acquired March 30, 2026 in joint venture with MetroNational and Radom Capital.",
    "signal_type": "capital", "fit_signal": "A current joint venture with two other firms screened here, so one relationship reaches three.",
    "url": "https://natlawreview.com/press-releases/metronational-grows-greater-houston-portfolio-landmark-m-k-t-heights"},
 ],
 "capital_signals": [
   {"text": "Joint venture with MetroNational and Radom Capital to acquire M-K-T Heights, 218,000 square feet, price undisclosed", "date": "2026-03-30",
    "url": "https://natlawreview.com/press-releases/metronational-grows-greater-houston-portfolio-landmark-m-k-t-heights"},
 ],
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 3, "capital_access": 2},
 "mvp_screen": "Clears all three. Mass timber at The Mill is documented method risk actually absorbed, not stated intent, and the 294-unit Aliana project is mobilisation scale in the right delivery window. Wall share is moderate because the mixed-use and wrap formats put more cost into structure and podium than into wall assembly. No disclosed dollar figure on any Triten capital event.",
 "sources": [
   {"url": "https://tritenre.com/news/this-historic-reuse-project-shows-the-latest-ways-timber-and-offices-are-changing-industrial-areas", "date": "2026-09-11"},
   {"url": "https://www.tritenre.com/about", "date": "2026-09-11"},
   {"url": "https://natlawreview.com/press-releases/metronational-grows-greater-houston-portfolio-landmark-m-k-t-heights", "date": "2026-03-30"},
 ],
 "audit_flags": ["No capital signal carries a dollar figure. M-K-T Heights price undisclosed.",
                 "The Mill square footage and unit count cross-checked across two sources with differing detail. Treat figures as approximate.",
                 "LinkedIn URLs unsourced for all four principals."],
 "hue_hex": "#8FA37E",
},
{
 "target_id": "HOU-007",
 "entity_name": "First America Homes",
 "entity_type": "homebuilder",
 "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "developers"],
 "region": "The Woodlands HQ / Liberty, Fort Bend",
 "homepage_url": "https://www.firstamericahomes.com/",
 "synopsis": "Homebuilding division of The Signorelli Company, ranked 75th on the 2026 Builder 100 list. Announced plans on August 6, 2026 to deliver more than 1,300 single-family homes across 14 new Texas communities, including the 359-home Azalea District at Valley Ranch in Liberty County priced from the $300,000s. Publishes its wall assembly as a marketing position.",
 "key_stat": "1,300+ homes across 14 new communities",
 "principals": [
   {"name": "John Winniford", "role": "President and Chief Executive Officer", "linkedin_url": None},
   {"name": "Danny Signorelli", "role": "Founder and Chief Executive Officer, The Signorelli Company", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Azalea District at Valley Ranch", "detail": "Liberty County. 359 homes priced from the $300,000s. Announced August 2026.",
    "signal_type": "repeatable", "fit_signal": "359 near-identical units on one site inside a masterplan the parent company controls. Land and vertical sit under one owner, so there is no third party to veto the method.",
    "url": "https://www.globenewswire.com/news-release/2026/08/06/3340350/0/en/Citing-strong-market-fundamentals-Signorelli-chooses-rapid-Texas-expansion-for-award-winning-homebuilding-division.html"},
   {"name": "Published wall-assembly position", "detail": "Company blog describes 2x6 advanced framing at 16-inch on-centre spacing, stated as 30 percent more lumber than typical, plus LP TopNotch 350 subfloor and pump-truck foundation pours.",
    "signal_type": "method_risk", "fit_signal": "A production builder that markets its wall assembly has already decided the wall is a competitive variable rather than a commodity. ",
    "url": "https://www.firstamericahomes.com/blog/first-america-homes-construction-the-real-difference-is-in-the-walls/"},
 ],
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 2, "capital_access": 2},
 "mvp_screen": "Clears all three. Detached single-family at 1,300-plus units a year is both repeatable and wall-heavy, and vertical integration with the parent land developer removes the usual split between who picks the lot and who picks the wall. Innovation appetite is partial: the firm optimises conventional framing rather than departing from it, which is appetite for wall performance without any evidence of appetite for a new method.",
 "sources": [
   {"url": "https://www.globenewswire.com/news-release/2026/08/06/3340350/0/en/Citing-strong-market-fundamentals-Signorelli-chooses-rapid-Texas-expansion-for-award-winning-homebuilding-division.html", "date": "2026-08-06"},
   {"url": "https://www.firstamericahomes.com/blog/first-america-homes-construction-the-real-difference-is-in-the-walls/", "date": None},
 ],
 "audit_flags": ["The wall-assembly blog post carries no publication date. Currency unconfirmed.",
                 "Advanced framing is a refinement of stick framing, not a non-standard system. Scored as partial appetite, not proven method risk.",
                 "No capital signal with a figure for First America Homes or its parent."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-008",
 "entity_name": "Meritage Homes Corporation",
 "entity_type": "homebuilder",
 "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "public"],
 "region": "Scottsdale HQ / Liberty, Harris",
 "homepage_url": "https://www.meritagehomes.com/",
 "synopsis": "NYSE-listed production homebuilder active in the Houston market. Co-acquired 309 acres with M/I Homes for Trinity Landing in Dayton, Liberty County, a 1,000-home community on 45, 50 and 60 foot lots, reported March 19, 2026. Reported a sub-110 calendar day construction schedule sustained for four consecutive quarters through Q1 2026.",
 "key_stat": "Sub-110 day cycle, 4 straight quarters",
 "principals": [
   {"name": "Phillippe Lord", "role": "Chief Executive Officer", "linkedin_url": None},
   {"name": "Hilla Sferruzza", "role": "Executive Vice President and Chief Financial Officer", "linkedin_url": None},
   {"name": "Steven J. Hilton", "role": "Executive Chairman of the Board", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Trinity Landing", "detail": "Dayton, Liberty County. 309 acres, 1,000 planned homes on 45, 50 and 60 foot lots. Co-acquired with M/I Homes, reported March 19, 2026.",
    "signal_type": "repeatable", "fit_signal": "1,000 units on narrow lots in one location. Narrow-lot product raises wall count per acre, which is the direction that favours a printed wall system.",
    "url": "https://houstonagentmagazine.com/2026/03/19/m-i-homes-meritage-homes-trinity-landing/"},
   {"name": "Cycle-time and AI programme", "detail": "Sub-110 calendar day construction schedule held for four consecutive quarters through Q1 2026. CEO describes deploying AI across every part of the business.",
    "signal_type": "schedule", "fit_signal": "A builder already measuring itself on cycle time has the internal metric a speed pitch has to move. The same transcript contains no mention of modular, panelized, ICF or SIPs, so the appetite is operational and has not yet reached the envelope.",
    "url": "https://www.investing.com/news/transcripts/earnings-call-transcript-meritage-homes-q1-2026-sees-earnings-miss-stock-dips-93CH-4633508"},
 ],
 "capital_signals": [],
 "quote": {"text": "AI is going to have a place in every sector of every business. I think it's just deployment and low-hanging fruit.",
           "speaker": "Phillippe Lord, Chief Executive Officer", "date": "2026-04-01",
           "url": "https://www.investing.com/news/transcripts/earnings-call-transcript-meritage-homes-q1-2026-sees-earnings-miss-stock-dips-93CH-4633508"},
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 2, "capital_access": 3},
 "mvp_screen": "Clears all three. A 1,000-home Houston-area position, listed-company balance sheet, and a documented technology posture with a named CEO on record. The qualification is that the appetite is confined to operations and AI. The Q1 2026 transcript affirmatively contains no mention of any alternative wall or structural system, so this is a builder who thinks about schedule but has not yet thought about the envelope.",
 "sources": [
   {"url": "https://houstonagentmagazine.com/2026/03/19/m-i-homes-meritage-homes-trinity-landing/", "date": "2026-03-19"},
   {"url": "https://www.investing.com/news/transcripts/earnings-call-transcript-meritage-homes-q1-2026-sees-earnings-miss-stock-dips-93CH-4633508", "date": "2026-04-01"},
 ],
 "audit_flags": ["Trinity Landing land purchase price not disclosed.",
                 "Meritage headquarters reported from general corporate record, not reconfirmed on an investor-relations page.",
                 "No Meritage statement on wall systems, modular or offsite located. Innovation score rests on operational technology only."],
 "hue_hex": "#8FA37E",
},
{
 "target_id": "HOU-009",
 "entity_name": "Century Communities, Inc.",
 "entity_type": "homebuilder",
 "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "public"],
 "region": "Greenwood Village HQ / Waller, Harris",
 "homepage_url": "https://www.centurycommunities.com/",
 "synopsis": "NYSE-listed production homebuilder. Announced Mirabella on September 10, 2026, a 1,200-home community on 318 acres in Brookshire, Waller County, with 18 floor plans from 1,388 to 2,657 square feet priced from the low $200,000s. Reported a company-record 112 calendar day average cycle time and a 5 percent quarter-over-quarter reduction in direct construction costs in Q2 2026.",
 "key_stat": "1,200 homes on 318 acres, Brookshire",
 "principals": [
   {"name": "Rob Francescon", "role": "Chief Executive Officer", "linkedin_url": None},
   {"name": "Tanya Rizzo", "role": "Houston Division President", "linkedin_url": None},
 ],
 "key_projects": [
   {"name": "Mirabella", "detail": "Brookshire, Waller County. 318 acres, approximately 1,200 homes, 18 floor plans from 1,388 to 2,657 square feet, priced from the low $200,000s. Announced September 10, 2026.",
    "signal_type": "repeatable", "fit_signal": "1,200 homes across only 18 plan types on a single site. Low plan variety against high unit count is the specific condition under which printer mobilisation amortises.",
    "url": "https://realtynewsreport.com/1200-design-forward-homes-coming-to-brookshire/"},
   {"name": "Cost and cycle-time programme", "detail": "Company-record 112 calendar day average cycle time and 5 percent quarter-over-quarter direct cost reduction in Q2 2026, attributed to cost initiatives launched at the end of 2025 rather than commodity prices.",
    "signal_type": "schedule", "fit_signal": "An active, executive-owned direct-cost reduction programme is the budget line a $20 per square foot wall claim competes for. No alternative-method adoption was mentioned in the same coverage.",
    "url": "https://www.housingwire.com/articles/century-communities-q2-2026-strategy/"},
 ],
 "capital_signals": [],
 "quote": {"text": "We're very pleased with the 5% reduction in directs on a quarter-over-quarter basis.",
           "speaker": "Rob Francescon, Chief Executive Officer", "date": "2026-07-23",
           "url": "https://www.housingwire.com/articles/century-communities-q2-2026-strategy/"},
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 2, "capital_access": 3},
 "mvp_screen": "Clears all three. The Mirabella plan count against unit count is the cleanest amortisation case among the listed builders, and there is a named Houston division president rather than only a corporate officer. Innovation appetite is inferred from an active direct-cost programme and record cycle times, not from any adoption of a non-standard method, so it is scored partial.",
 "sources": [
   {"url": "https://realtynewsreport.com/1200-design-forward-homes-coming-to-brookshire/", "date": "2026-09-10"},
   {"url": "https://www.housingwire.com/articles/century-communities-q2-2026-strategy/", "date": "2026-07-23"},
 ],
 "audit_flags": ["No Century Communities statement on modular, panelized or printed construction located.",
                 "Headquarters reported from general corporate record, not reconfirmed on a company page.",
                 "LinkedIn URLs unsourced for both principals."],
 "hue_hex": "#8FA37E",
},
]
