# -*- coding: utf-8 -*-
"""Tier B and tail records. Compact form expanded by build.py."""

def P(*pairs):
    return [{"name": n, "role": r, "linkedin_url": None} for n, r in pairs]

def PJ(*triples):
    return [{"name": n, "detail": d, "signal_type": s, "fit_signal": f, "url": u}
            for n, d, s, f, u in triples]

def S(*pairs):
    return [{"url": u, "date": d} for u, d in pairs]

def C(*triples):
    return [{"text": t, "date": d, "url": u} for t, d, u in triples]


REST = [
# ---------------------------------------------------------------- TIER B
{
 "target_id": "HOU-010", "entity_name": "Camillo Companies (SimplyHome / Legend Homes)",
 "entity_type": "btr_developer", "entity_role": "vertical_buyer",
 "categories": ["build_to_rent", "homebuilders"], "region": "Houston HQ, Harris County",
 "homepage_url": "https://www.camillocompanies.com/",
 "synopsis": "Houston real estate group founded in 1989 running three brands: SimplyHome single-family build-to-rent, with more than 10,800 rental homes across 115-plus communities as of August 2026, Legend Homes for-sale production housing, and Academy Development. Holds 25,000 to 35,000 residential lots owned or in development at any time.",
 "key_stat": "10,800+ rental homes, 115+ communities",
 "principals": P(("Margaret Potter", "Chief Executive Officer"), ("Meagan Yager", "Vice President of Marketing")),
 "key_projects": PJ(
   ("SimplyHome portfolio", "More than 10,800 single-family rental homes built across 115-plus communities as of August 2026.",
    "repeatable", "The highest built-and-held unit count screened. Builds, owns and manages, so schedule savings and wall durability both land on the same balance sheet.",
    "https://www.camillocompanies.com/blog/simplyhome-celebrates-its-10000th-home-constructed"),
   ("Lot bank", "25,000 to 35,000 residential lots owned or in development at any time, reported March 7, 2023.",
    "repeatable", "A standing lot bank of this size converts directly into forward unit volume without new land assembly.",
    "https://www.housingwire.com/articles/camillo-weds-its-brand-family-with-a-newly-spoken-vow-opening-doors/")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 2},
 "mvp_screen": "Two of three hold, and the combination of repeatable volume and wall-heavy product is among the largest in Greater Houston. Track record is the failure: no construction-method, technology or labour statement of any kind is published, only workplace awards and a trade-in programme. A conversion target rather than a warm one.",
 "sources": S(("https://www.camillocompanies.com/our-companies", "2026-09-11"),
              ("https://www.housingwire.com/articles/camillo-weds-its-brand-family-with-a-newly-spoken-vow-opening-doors/", "2023-03-07"),
              ("https://www.camillocompanies.com/blog/simplyhome-celebrates-its-10000th-home-constructed", "2026-08-01")),
 "audit_flags": ["Dedicated innovation-appetite search returned no construction-method or technology content. Scored zero on evidence, not on inference.",
                 "No named or dated individual Houston community with a unit count. Aggregate figures only.",
                 "No capital signal with a figure."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-011", "entity_name": "Howard Hughes Holdings Inc.",
 "entity_type": "mpc_developer", "entity_role": "channel",
 "categories": ["mpc", "public", "developers"], "region": "The Woodlands HQ / Harris, Montgomery",
 "homepage_url": "https://www.howardhughes.com/",
 "synopsis": "NYSE-listed master-planned community developer behind The Woodlands, begun 1974, and Bridgeland, 11,400 acres with construction begun October 2003 and roughly 65,000 residents projected at 2037 buildout. Broke ground on The Woodlands Hills, 2,000 acres and 4,500-plus residences, on November 15, 2017. Pershing Square invested $900 million on May 5, 2025 for 46.9 percent ownership.",
 "key_stat": "$900M Pershing Square investment, 46.9%",
 "principals": P(("David O'Reilly", "Chief Executive Officer"), ("Bill Ackman", "Executive Chairman of the Board"),
                 ("Ryan Israel", "Chief Investment Officer"), ("Jim Carman", "President, Houston Region")),
 "key_projects": PJ(
   ("Bridgeland", "Cypress, Harris County. 11,400 acres, construction begun October 2003, home sales from 2006, roughly 65,000 residents projected at 2037 buildout.",
    "resilience", "A 900-acre lake and detention network with eight feet of freeboard exceeded Harris County Flood Control District requirements. ULI records no homes taking on water in either the April 2016 Tax Day Flood or Hurricane Harvey in August 2017. Evidence this developer already pays for engineered resilience.",
    "https://developingresilience.uli.org/case/bridgeland/"),
   ("The Woodlands Hills", "Conroe and Willis, Montgomery County. 2,000 acres, more than 4,500 planned residences. Groundbreaking November 15, 2017.",
    "repeatable", "4,500-plus residences in one location, though delivered by third-party builders on Howard Hughes lots rather than by Howard Hughes.",
    "https://investor.howardhughes.com/news-releases/news-release-details/howard-hughes-corporationr-breaks-ground-woodlands-hills"),
   ("LEED for Communities precertification", "Bridgeland and The Woodlands precertified by USGBC on July 14, 2022.",
    "resilience", "Programme-level sustainability commitment. The Q1 2026 earnings call contains no mention of construction technology, method, labour or cycle time.",
    "https://www.bridgeland.com/news/the-howard-hughes-communities-of-bridgeland-and-the-woodlands-earn-leed-precertification/")),
 "capital_signals": C(("Pershing Square invested $900 million for nine million newly issued shares at $100.00, a 48 percent premium, taking 46.9 percent ownership", "2025-05-05",
                       "https://www.globenewswire.com/news-release/2025/05/05/3073918/0/en/Pershing-Square-to-Invest-900-million-to-Acquire-Nine-Million-Newly-Issued-Shares-of-Howard-Hughes-Holdings-and-Transform-HHH-Into-a-Diversified-Holding-Company.html")),
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 1, "capital_access": 3},
 "mvp_screen": "Scale and capital are unmatched and the Bridgeland flood record is the best resilience evidence in the roster. It lands in tier two because of role, not size. Howard Hughes develops land and infrastructure and sells lots to builders, so it does not buy wall systems for its residential product. Its value is as a channel: it sets builder rosters and architectural standards across 11,400 acres. Direct vertical purchasing exists only in its commercial and multifamily development.",
 "sources": S(("https://developingresilience.uli.org/case/bridgeland/", "2026-09-11"),
              ("https://www.globenewswire.com/news-release/2025/05/05/3073918/0/en/Pershing-Square-to-Invest-900-million-to-Acquire-Nine-Million-Newly-Issued-Shares-of-Howard-Hughes-Holdings-and-Transform-HHH-Into-a-Diversified-Holding-Company.html", "2025-05-05"),
              ("https://www.bridgeland.com/news/the-howard-hughes-communities-of-bridgeland-and-the-woodlands-earn-leed-precertification/", "2022-07-14")),
 "audit_flags": ["Q1 2026 earnings call contains no mention of construction technology, automation, modular, offsite, labour or cycle time.",
                 "Channel role means the wall-system buyer is the builder on the lot, not Howard Hughes. Confirm which entity holds vertical scope before pitching."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-012", "entity_name": "M/I Homes, Inc.", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "public"], "region": "Columbus HQ / Liberty, Harris",
 "homepage_url": "https://www.mihomes.com/",
 "synopsis": "NYSE-listed production homebuilder whose Houston division co-acquired 309 acres with Meritage Homes for the 1,000-home Trinity Landing community in Dayton, Liberty County, its third Houston-area land acquisition in six months as of March 19, 2026.",
 "key_stat": "3 Houston land deals in 6 months",
 "principals": P(("Bob Schottenstein", "Chief Executive Officer"), ("Jay McManus", "Houston Division President")),
 "key_projects": PJ(
   ("Trinity Landing", "Dayton, Liberty County. 309 acres, 1,000 homes, co-acquired with Meritage Homes, reported March 19, 2026.",
    "repeatable", "1,000 units on one site. The Houston division president describes the east Houston Grand Parkway corridor as newly viable for volume production.",
    "https://houstonagentmagazine.com/2026/03/19/m-i-homes-meritage-homes-trinity-landing/")),
 "capital_signals": [],
 "quote": {"text": "Reduced cycle time has helped. It doesn't take us as long to get houses built as it did a year ago.",
           "speaker": "Bob Schottenstein, Chief Executive Officer", "date": "2026-04-01",
           "url": "https://www.investing.com/news/transcripts/earnings-call-transcript-mi-homes-q1-2026-surpasses-eps-forecast-93CH-4629998"},
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 1, "capital_access": 3},
 "mvp_screen": "Repeatability, wall share and capital all hold. Innovation appetite is thin: the CEO references reduced cycle time only in the context of spec-inventory management, with no detail on what enabled it, and the Q1 2026 transcript contains no mention of modular, panelized, offsite, robotics or AI. A named local division president buying land three times in six months is the access advantage here.",
 "sources": S(("https://houstonagentmagazine.com/2026/03/19/m-i-homes-meritage-homes-trinity-landing/", "2026-03-19"),
              ("https://www.investing.com/news/transcripts/earnings-call-transcript-mi-homes-q1-2026-surpasses-eps-forecast-93CH-4629998", "2026-04-01")),
 "audit_flags": ["Trinity Landing land price not disclosed.", "No method or wall-system statement located."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-013", "entity_name": "Perry Homes", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders"], "region": "Houston HQ, Harris County",
 "homepage_url": "https://www.perryhomes.com/",
 "synopsis": "Privately held Houston homebuilder founded in 1967 by Bob Perry. Operates more than 120 communities and has sold over 65,000 homes across Dallas-Fort Worth, Austin, Houston and San Antonio. Active builder in Austin Point and Sienna.",
 "key_stat": "120+ communities, 65,000+ homes sold",
 "principals": P(("Kathy Britton", "Owner and Executive Chair"), ("Todd Chachere", "Chief Executive Officer")),
 "key_projects": PJ(
   ("Houston community programme", "More than 120 active communities across four Texas markets, including builder roles at Austin Point in Rosenberg and Sienna in Missouri City.",
    "repeatable", "Detached single-family at this volume with a Houston headquarters. Wall-heavy product and decision-making in the same city as the printer.",
    "https://www.perryhomes.com/about-perry-homes"),
   ("Innovation positioning", "Company page dated October 5, 2021 defines innovation as smart-home technology, recycled materials in general terms, contemporary floor plans and 360-degree tours.",
    "schedule", "The firm's own definition of innovation contains no construction method, wall system or structural technology. Appetite is in the product feature set, not the build.",
    "https://www.perryhomes.com/company-news/perry-homes-standard-for-innovative-homes")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 1, "capital_access": 2},
 "mvp_screen": "Product fit is excellent and the firm is locally owned and locally run, which shortens the decision path. Innovation appetite is the gap and the evidence is unusually clear about it: Perry published its own definition of innovation and no part of it touches how the building is built.",
 "sources": S(("https://www.perryhomes.com/about-perry-homes", "2026-09-11"),
              ("https://www.perryhomes.com/company-news/perry-homes-standard-for-innovative-homes", "2021-10-05"),
              ("https://houston.culturemap.com/03-08-22-perry-homes-new-ceo-todd-chachere-kathy-britton-bob-perry/", "2022-03-08")),
 "audit_flags": ["No Houston-specific community unit counts or acreage sourced.", "No capital signal with a figure."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-014", "entity_name": "LGI Homes, Inc.", "entity_type": "homebuilder", "entity_role": "vertical_buyer",
 "categories": ["homebuilders", "public"], "region": "The Woodlands HQ, Montgomery County",
 "homepage_url": "https://www.lgihomes.com/",
 "synopsis": "NASDAQ-listed production homebuilder headquartered at 1450 Lake Robbins Drive in The Woodlands, operating more than 185 new-home communities nationally and reporting closings monthly.",
 "key_stat": "185+ communities, Houston-area HQ",
 "principals": P(("Eric Lipar", "Chief Executive Officer and Chairman of the Board"),
                 ("Mike Snider", "President and Chief Operating Officer"),
                 ("Charles Merdian", "Chief Financial Officer and Treasurer")),
 "key_projects": PJ(
   ("National community programme", "More than 185 new-home communities, entry-level product, headquartered in the Houston metro.",
    "repeatable", "The most standardised product line among the listed builders and a head office inside the target geography. Entry-level detached housing puts a high share of cost in the wall.",
    "https://www.lgihomes.com/")),
 "capital_signals": [],
 "scores": {"repeatability": 3, "wall_share": 3, "innovation": 0, "capital_access": 3},
 "mvp_screen": "Two of three hold strongly. A full-text review of the Q2 2026 earnings call transcript from August 11, 2026 found zero mentions of labour, construction technology, automation, robotics, AI, modular, panelized, offsite, 3D printing, innovation, cycle time, cost per square foot or building method. The call covered closings, backlog, margins, debt and geography only. That is a documented absence, not a research gap, and it is why a company headquartered twenty minutes from Bridgeland sits in tier two.",
 "sources": S(("https://www.fool.com/earnings/call-transcripts/2026/08/11/lgi-homes-lgih-q2-2026-earnings-call-transcript/", "2026-08-11"),
              ("https://www.globenewswire.com/news-release/2026/09/04/3356358/28788/en/LGI-Homes-Inc-Reports-August-2026-Home-Closings.html", "2026-09-04")),
 "audit_flags": ["Q2 2026 transcript reviewed in full. Zero construction-method or technology mentions. Innovation scored zero on evidence.",
                 "No named Houston-area community with a unit count located. Closings reported in aggregate."],
 "hue_hex": "#E8A33D",
},
{
 "target_id": "HOU-015", "entity_name": "The Signorelli Company", "entity_type": "mpc_developer", "entity_role": "channel",
 "categories": ["mpc", "developers"], "region": "The Woodlands HQ / Fort Bend, Liberty",
 "homepage_url": "https://www.signorellicompany.com/",
 "synopsis": "Privately held developer with more than 16 master-planned communities and over 23,000 paper lots in pipeline as of August 6, 2026. Developer of Austin Point in Rosenberg, cited at 4,700 to 6,400 acres with roughly 14,000 planned homes, announced September 22, 2023, and Valley Ranch in Liberty County with 2.55 million square feet of retail, 2,000-plus single-family homes and 1,000 multifamily units.",
 "key_stat": "23,000+ paper lots in pipeline",
 "principals": P(("Danny Signorelli", "Founder and Chief Executive Officer"), ("Jeff Dewese", "President, Land Division"),
                 ("Harry Dinham", "Chief Financial Officer")),
 "key_projects": PJ(
   ("Austin Point", "Rosenberg, Fort Bend County. Roughly 14,000 planned homes. Phase I approximately 400 homes, groundbreaking 2024, sales from spring 2025. Builder roster includes Ashton Woods, Beazer, Drees, CastleRock, David Weekley, Perry and Westin.",
    "repeatable", "Fourteen thousand homes under one masterplan with a builder roster the developer selects. The single largest forward unit pool screened.",
    "https://shoppingcenterbusiness.com/signorelli-co-announces-phase-i-of-4700-acre-master-planned-development-near-houston/"),
   ("Owned homebuilding division", "First America Homes is a Signorelli company, ranked 75th on the 2026 Builder 100 list.",
    "method_risk", "Land and vertical under one owner. Signorelli can specify a wall method on its own lots through its own builder without a third-party veto, which no other master-planned developer screened can do.",
    "https://www.globenewswire.com/news-release/2026/08/06/3340350/0/en/Citing-strong-market-fundamentals-Signorelli-chooses-rapid-Texas-expansion-for-award-winning-homebuilding-division.html")),
 "capital_signals": [],
 "quote": {"text": "We're not building yesterday's MPC. This isn't about cookie-cutter subdivisions.",
           "speaker": "Danny Signorelli, Chief Executive Officer", "date": "2025-05-28",
           "url": "https://www.housingwire.com/articles/signorelli-builds-boldly-where-others-shy-away-from-risk/"},
 "scores": {"repeatability": 3, "wall_share": 1, "innovation": 1, "capital_access": 2},
 "mvp_screen": "Scores as a land developer, which is what it is: wall share is low because Signorelli sells lots rather than pouring walls. Its strategic value is higher than its score. It owns First America Homes, which holds all three counts, so one relationship reaches both the largest lot pipeline in Greater Houston and a builder that already markets its wall assembly. Approach the pair together.",
 "sources": S(("https://shoppingcenterbusiness.com/signorelli-co-announces-phase-i-of-4700-acre-master-planned-development-near-houston/", "2023-09-22"),
              ("https://www.globenewswire.com/news-release/2026/08/06/3340350/0/en/Citing-strong-market-fundamentals-Signorelli-chooses-rapid-Texas-expansion-for-award-winning-homebuilding-division.html", "2026-08-06"),
              ("https://www.housingwire.com/articles/signorelli-builds-boldly-where-others-shy-away-from-risk/", "2025-05-28")),
 "audit_flags": ["Austin Point acreage cited as both 4,700 and 6,400 acres in different releases. Not reconciled.",
                 "The cookie-cutter quote concerns land use and commercial mix, not construction method. It is not evidence of a track record.",
                 "No capital signal with a figure."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-016", "entity_name": "Commander Home Builders", "entity_type": "homebuilder", "entity_role": "proven_adopter",
 "categories": ["homebuilders", "proven_3dp"], "region": "San Leon, Galveston County",
 "homepage_url": None, "no_web_presence": True,
 "synopsis": "Builder of Gulf Shore Estates in San Leon, roughly 40 miles southeast of downtown Houston, where 23 of 26 planned homes are to be 3D printed in partnership with HiveASMBLD. Homes run 1,000 to 2,100 square feet priced from the low $200,000s to about $385,000, announced early April 2026.",
 "key_stat": "23 of 26 homes 3D printed",
 "principals": P(("Steve Commander", "Owner")),
 "key_projects": PJ(
   ("Gulf Shore Estates", "San Leon, Galveston County. 26 homes planned, 23 to be 3D printed after three conventional builds. 1,000 to 2,100 square feet, low $200,000s to about $385,000. Announced April 2026.",
    "method_risk", "A builder who built three conventionally, then committed the remaining 23 to printing. The owner states construction timeline fell roughly 50 percent with 5 to 7 percent cost savings reinvested into upgrades. This is a Houston-market operator quoting real printed-wall performance.",
    "https://www.homes.com/news/houstons-3d-printed-housing-push-grows-with-two-new-developments/647676272/")),
 "capital_signals": [],
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 3, "capital_access": 1},
 "mvp_screen": "Innovation and wall share are maximal: this operator has already bought printed walls and will speak to their economics on the record. Repeatability is moderate at 26 units and capital is unevidenced with no confirmed corporate web presence. Currently supplied by HiveASMBLD. Value here is partly as a prospect and partly as the market's only independent reference on printed-wall performance in a Gulf Coast county.",
 "sources": S(("https://www.homes.com/news/houstons-3d-printed-housing-push-grows-with-two-new-developments/647676272/", "2026-04-01")),
 "audit_flags": ["Currently building with HiveASMBLD, a Houston competitor.",
                 "No corporate homepage confirmed. Entity structure unverified.",
                 "Timeline and cost-savings figures are the owner's own statements, not independently verified."],
 "hue_hex": "#FF4F00",
},
{
 "target_id": "HOU-017", "entity_name": "Elpis 3D Home Builders", "entity_type": "homebuilder", "entity_role": "proven_adopter",
 "categories": ["homebuilders", "proven_3dp"], "region": "East End Houston, Harris County",
 "homepage_url": None, "no_web_presence": True,
 "synopsis": "Builder of Avenue J, a two-unit 3D-printed duplex in Houston's East End of roughly 1,727 square feet per unit priced at $365,000 each, built in partnership with HiveASMBLD. Construction started March 2026 with a June 2026 move-in target.",
 "key_stat": "Duplex, ~1,727 sf per unit, $365,000",
 "principals": P(("Tony M. Brown", "Principal")),
 "key_projects": PJ(
   ("Avenue J", "East End Houston, Harris County. Two-unit duplex, roughly 1,727 square feet per unit at $365,000 each. Construction started March 2026, move-in targeted June 2026.",
    "method_risk", "Attached party-wall product delivered by printing, inside the city limits, on a roughly three-month cycle. Small, but it is a completed Houston reference for printed party walls.",
    "https://www.homes.com/news/houstons-3d-printed-housing-push-grows-with-two-new-developments/647676272/")),
 "capital_signals": [],
 "scores": {"repeatability": 1, "wall_share": 3, "innovation": 3, "capital_access": 1},
 "mvp_screen": "Proven adopter, but a single duplex does not meet the repeatability screen and no capital is evidenced. Included because it completes the picture of who is actually buying printed walls in Harris County, and because a two-unit reference inside the city limits is useful to any subsequent pitch.",
 "sources": S(("https://www.homes.com/news/houstons-3d-printed-housing-push-grows-with-two-new-developments/647676272/", "2026-01-01")),
 "audit_flags": ["Currently building with HiveASMBLD.", "No corporate homepage confirmed.",
                 "Houston Chronicle coverage of this project blocked by robots.txt and not read."],
 "hue_hex": "#FF4F00",
},
{
 "target_id": "HOU-018", "entity_name": "NewQuest Properties", "entity_type": "retail_developer", "entity_role": "vertical_buyer",
 "categories": ["retail", "mixed_use", "developers"], "region": "Houston HQ / Fort Bend, Brazoria",
 "homepage_url": "https://www.newquest.com/",
 "synopsis": "Houston retail developer managing a 12 million square foot portfolio valued at $3.1 billion. Master developer of a repeated Town Center format across Greater Houston including Fort Bend Town Center in Missouri City, Cy-Fair Town Center, Stone Hill Town Center and the 800,000 square foot Pearland Town Center Mall.",
 "key_stat": "$3.1B portfolio, 12M sf managed",
 "principals": P(("Steven D. Alvis", "Co-Founder and Managing Partner"), ("Jay K. Sears", "Co-Founder and Managing Partner"),
                 ("Austin Alvis", "President and Chief Development Officer"), ("Jeff Horton", "Chief Operating Officer and Head of Capital Markets")),
 "key_projects": PJ(
   ("Town Center format", "A branded, repeated retail and mixed-use format deployed at a minimum of five distinct Houston-area sites across Harris, Fort Bend, Galveston and Brazoria counties.",
    "repeatable", "A named, repeated building format across multiple counties. Retail shell buildings are single-storey and wall-dominant, which suits a printed wall system, though tilt-wall concrete is already the cheap incumbent in this product type.",
    "https://www.newquest.com/about-us/"),
   ("Fort Bend Town Center", "Missouri City, Fort Bend County. Phase III leasing under way as of December 2025.",
    "repeatable", "Active phased delivery inside an existing masterplan, so successive phases can carry a method proven in an earlier one.",
    "https://communityimpact.com/houston/sugar-land-missouri-city/development/2025/12/11/leasing-underway-for-remaining-2-phases-in-fort-bend-town-center/")),
 "capital_signals": C(("$3.1 billion owned-asset portfolio value and 12 million square feet of managed retail, company-stated", "2026-09-11",
                       "https://www.newquest.com/about-us/")),
 "scores": {"repeatability": 3, "wall_share": 2, "innovation": 1, "capital_access": 3},
 "mvp_screen": "Repeatability and capital are strong and the format is genuinely replicated. Two qualifications keep it out of tier one. Retail shells compete against tilt-wall concrete, which already delivers low-cost walls fast, so the $20 per square foot advantage is measured against a tougher incumbent than in residential. And no innovation-appetite evidence was found. The $3.1 billion figure is company-stated rather than filed.",
 "sources": S(("https://www.newquest.com/about-us/", "2026-09-11"),
              ("https://communityimpact.com/houston/sugar-land-missouri-city/development/2025/12/11/leasing-underway-for-remaining-2-phases-in-fort-bend-town-center/", "2025-12-11")),
 "audit_flags": ["$3.1 billion portfolio value is company-stated, not from a filing.",
                 "Tilt-wall is the incumbent in this product type. Competitive comparison differs from residential."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-019", "entity_name": "Camden Property Trust", "entity_type": "reit", "entity_role": "vertical_buyer",
 "categories": ["build_to_rent", "public", "multifamily"], "region": "Houston HQ / Fort Bend, Montgomery",
 "homepage_url": "https://www.camdenliving.com/",
 "synopsis": "NYSE-listed multifamily REIT headquartered in Houston. Invested $155 million in two Houston-suburb build-to-rent communities: Camden Long Meadow Farms in Richmond, Fort Bend County, at $80 million for 200 homes, and Camden Woodmill Creek in The Woodlands, Montgomery County, at $75 million for 189 homes, reported December 9, 2022. Alex Jessett was named Chief Executive Officer on March 27, 2026.",
 "key_stat": "$155M into 389 BTR homes",
 "principals": P(("Alex Jessett", "Chief Executive Officer"), ("Richard J. Campo", "Executive Chairman of the Board of Trust Managers")),
 "key_projects": PJ(
   ("Camden Long Meadow Farms", "Richmond, Fort Bend County. 200 build-to-rent homes, $80 million.",
    "repeatable", "200 detached rental units on one site, owned and held by the developer. Durability and insurance outcomes accrue to the same owner over decades.",
    "https://therealdeal.com/texas/houston/2022/12/09/camden-property-trusts-155m-leap-into-build-to-rent/"),
   ("Camden Woodmill Creek", "The Woodlands, Montgomery County. 189 build-to-rent homes, $75 million.",
    "repeatable", "A second concurrent build-to-rent community in the same metro, confirming a programme rather than a one-off.",
    "https://therealdeal.com/texas/houston/2022/12/09/camden-property-trusts-155m-leap-into-build-to-rent/")),
 "capital_signals": C(("$155 million committed across two Houston build-to-rent communities, $80 million for 200 homes and $75 million for 189 homes", "2022-12-09",
                       "https://therealdeal.com/texas/houston/2022/12/09/camden-property-trusts-155m-leap-into-build-to-rent/")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 3},
 "mvp_screen": "Houston-headquartered, listed, long-term holder of detached rental product with committed dollar figures on the record, which few Houston holders publish. Two gaps: the build-to-rent figures date to December 2022 and have not been refreshed from a later 10-K, and no method evidence of any kind is published. New chief executive as of March 2026, which is often when method decisions reopen.",
 "sources": S(("https://therealdeal.com/texas/houston/2022/12/09/camden-property-trusts-155m-leap-into-build-to-rent/", "2022-12-09"),
              ("https://www.bisnow.com/news/national/multifamily/camden-property-trust-names-new-ceo-co-founder-campo-steps-back-133855", "2026-03-27")),
 "audit_flags": ["Build-to-rent capital figures date to December 2022. Camden 10-K and 10-Q filings not pulled in this pass and almost certainly itemise further Houston development starts.",
                 "No innovation-appetite evidence located."],
 "hue_hex": "#5B7C99",
},
{
 "target_id": "HOU-020", "entity_name": "Provident Realty Advisors", "entity_type": "pe_developer", "entity_role": "capital",
 "categories": ["capital", "build_to_rent", "developers"], "region": "Dallas HQ / Baytown, Harris-Chambers",
 "homepage_url": "https://provident.net/",
 "synopsis": "Dallas developer with $7.5 billion invested since 1991 and a $2.9 billion current portfolio. Entered the Houston industrial market with the $124 million, 1.28 million square foot Port 99 project near Baytown announced July 17, 2023, and launched the parcHAUS build-to-rent offering on March 24, 2022 targeting seven single-family rental communities across Texas.",
 "key_stat": "$7.5B invested since 1991",
 "principals": P(("Leon J. Backes", "Founder and Chief Executive Officer"),
                 ("Christen Vestal", "Director of Development and Acquisitions, Houston")),
 "key_projects": PJ(
   ("parcHAUS build-to-rent programme", "Private equity offering launched March 24, 2022 targeting seven single-family rental communities across Texas, with 18 to 22 percent target IRR and a 1.9 to 2.2 times target equity multiple.",
    "repeatable", "A named, funded programme to build the same rental product seven times. Specific Houston-area sites are not named in the source.",
    "https://benzinga.com/real-estate/22/03/26269992/dallas-based-real-estate-developer-launches-private-equity-offering-for-development-of-build-to-rent"),
   ("Port 99", "Near Baytown on the Harris and Chambers county line. 1.28 million square feet across two buildings on 104 acres, $124 million. Announced July 17, 2023. First Provident location outside Dallas.",
    "capital", "A committed Houston-market position with a disclosed figure, and the reason a named development director sits in Houston.",
    "https://baytownedf.org/news/article/dallas-based-developer-provident-realty-advisors-enters-houston-industrial-market-with-124m-project")),
 "capital_signals": C(("$7.5 billion invested since 1991 against a $2.9 billion current portfolio, company-stated", "2026-09-11", "https://provident.net/"),
                      ("$124 million Port 99 industrial development near Baytown", "2023-07-17",
                       "https://baytownedf.org/news/article/dallas-based-developer-provident-realty-advisors-enters-houston-industrial-market-with-124m-project")),
 "scores": {"repeatability": 2, "wall_share": 3, "innovation": 0, "capital_access": 3},
 "mvp_screen": "The strongest capital position in the independently sourced capital layer, with a named Houston development director rather than a distant fund officer. The parcHAUS programme is exactly the repeatable rental format that suits a printed wall. No innovation-appetite evidence, and the Houston build-to-rent sites are not individually named, so the repeatability claim for this metro is programme-level rather than site-level.",
 "sources": S(("https://provident.net/", "2026-09-11"),
              ("https://baytownedf.org/news/article/dallas-based-developer-provident-realty-advisors-enters-houston-industrial-market-with-124m-project", "2023-07-17"),
              ("https://benzinga.com/real-estate/22/03/26269992/dallas-based-real-estate-developer-launches-private-equity-offering-for-development-of-build-to-rent", "2022-03-24")),
 "audit_flags": ["No parcHAUS Houston-area site named in public sources. Houston build-to-rent presence is programme-level only.",
                 "Portfolio figures are company-stated."],
 "hue_hex": "#5B7C99",
},
]
