# -*- coding: utf-8 -*-
"""Build 87. What kind of firm each card is, and which side of a printer sale it sits on.

A reader opening a card asks first what kind of company it is, and whether it
would buy a printer or pay someone who owns one. Each card carries both:

  role  buyer   would own and run the printer: small and mid-sized builders,
                which ICON names as Titan's market (the Field view), and the
                contractors and plants that build walls
        client  pays a builder or contractor to build: developers, owners,
                public agencies, general contractors that hire out their walls,
                and national builders, which buy through a national desk
        land    sells lots to builders
  kind  a few words from the card's own text: "Tilt-up concrete contractor"

Every card on either deck is listed here by id, and the build stops on a card
with no entry, an entry for a card that is not on the deck, or a role outside
the three. A firm on both decks takes the same role on both.
"""

ROLE_LABEL = {"buyer": "Printer buyer", "client": "Client", "land": "Land owner"}
# The key under the List. Most builders hire out their walls, so "buyer" is not
# "has its own crews". It is the firm that would own and run the machine: the
# builders ICON names as Titan's market and the trades and plants that make walls.
ROLE_NOTE = {
    "buyer": "Would own and run the printer: small and mid-sized builders, the Titan market ICON names, "
             "and the contractors and plants that build walls.",
    "client": "Pays a builder or contractor to build: developers, owners, public agencies, general "
              "contractors that hire out their walls, and national builders, which buy through a national desk.",
    "land": "Sells lots to builders.",
}
ROLES = ("buyer", "client", "land")

KIND = {
    # Greater Houston
    "HOU-002": ("buyer", "Homebuilder, printed homes"),
    "HOU-016": ("buyer", "Homebuilder, printed homes"),
    "HOU-017": ("buyer", "Homebuilder, printed duplex"),
    "HOU-123": ("buyer", "ICF homebuilder"),
    "HOU-001": ("buyer", "Build-to-rent developer and builder"),
    "HOU-126": ("buyer", "Modular homebuilder"),
    "HOU-060": ("buyer", "Production homebuilder"),
    "HOU-061": ("buyer", "Production homebuilder"),
    "HOU-073": ("buyer", "Production homebuilder"),
    "HOU-168": ("buyer", "Production and rental homebuilder"),
    "HOU-003": ("client", "Public housing authority"),
    "HOU-130": ("buyer", "Production homebuilder"),
    "HOU-074": ("buyer", "Entry-level homebuilder"),
    "HOU-131": ("buyer", "Active-adult homebuilder"),
    "HOU-010": ("buyer", "Build-to-rent builder and owner"),
    "HOU-022": ("buyer", "Production homebuilder"),
    "HOU-136": ("buyer", "Build-to-rent builder"),
    "HOU-122": ("buyer", "Custom homebuilder, concrete panel walls"),
    "HOU-007": ("buyer", "Production homebuilder"),
    "HOU-004": ("buyer", "Townhome builder"),
    "HOU-127": ("client", "Manufactured-home community developer"),
    "HOU-125": ("buyer", "Custom homebuilder"),
    "HOU-124": ("buyer", "Custom coastal homebuilder"),
    "HOU-135": ("buyer", "Build-on-your-lot homebuilder"),
    "HOU-068": ("buyer", "Semi-custom homebuilder"),
    "HOU-064": ("buyer", "Affordable production homebuilder"),
    "HOU-076": ("buyer", "Entry-level homebuilder, a David Weekley line"),
    "HOU-071": ("buyer", "Family homebuilder"),
    "HOU-063": ("buyer", "Family homebuilder"),
    "HOU-066": ("buyer", "Infill homebuilder"),
    "HOU-062": ("buyer", "Production homebuilder"),
    "HOU-128": ("client", "Commercial property owner"),
    "HOU-020": ("client", "Industrial and rental developer"),
    "HOU-075": ("buyer", "Production homebuilder"),
    "HOU-026": ("client", "Build-to-rent operator"),
    "HOU-033": ("buyer", "Production homebuilder, a Dream Finders brand"),
    "HOU-069": ("buyer", "Production homebuilder"),
    "HOU-077": ("buyer", "Production homebuilder"),
    "HOU-035": ("client", "Nonprofit housing developer"),
    "HOU-045": ("buyer", "Production homebuilder"),
    "HOU-067": ("buyer", "Semi-custom homebuilder"),
    "HOU-044": ("buyer", "Build-to-rent builder"),
    "HOU-070": ("buyer", "Semi-custom homebuilder"),
    "HOU-028": ("buyer", "Apartment developer with its own builder"),
    "HOU-152": ("buyer", "Steel framing contractor"),
    "HOU-146": ("buyer", "Wall panel and truss plant"),
    "HOU-139": ("buyer", "Precast concrete plant"),
    "HOU-120": ("buyer", "ICF wall contractor"),
    "HOU-104": ("buyer", "Concrete contractor"),
    "HOU-156": ("buyer", "Masonry contractor"),
    "HOU-101": ("buyer", "Concrete placement contractor"),
    "HOU-121": ("buyer", "Drywall and interiors contractor"),
    "HOU-162": ("buyer", "Shotcrete contractor"),
    "HOU-143": ("buyer", "Precast concrete plant"),
    "HOU-129": ("client", "Design-build firm"),
    "HOU-157": ("buyer", "Masonry and stone contractor"),
    "HOU-137": ("buyer", "Precast concrete plant"),
    "HOU-117": ("client", "Apartment general contractor"),
    "HOU-147": ("buyer", "Building products supplier and panel plants"),
    "HOU-155": ("buyer", "Masonry contractor"),
    "HOU-141": ("buyer", "Precast concrete plant"),
    "HOU-106": ("buyer", "Tilt-up concrete contractor"),
    "HOU-102": ("buyer", "General contractor with its own concrete crews"),
    "HOU-142": ("buyer", "Precast concrete plant"),
    "HOU-112": ("buyer", "Tilt-up concrete contractor"),
    "HOU-151": ("buyer", "Wall panel plants"),
    "HOU-149": ("buyer", "Wall panel and truss plant"),
    "HOU-144": ("buyer", "Precast concrete plant"),
    "HOU-138": ("buyer", "Hollowcore plank plant"),
    "HOU-105": ("buyer", "Tilt-up concrete contractor"),
    "HOU-145": ("buyer", "Precast concrete plant"),
    "HOU-114": ("client", "General contractor, tilt-up"),
    "HOU-165": ("buyer", "Foundation contractor"),
    "HOU-161": ("buyer", "Concrete pumping company"),
    "HOU-103": ("buyer", "Tilt-up concrete contractor"),
    "HOU-140": ("buyer", "Precast concrete plant"),
    "HOU-150": ("buyer", "Truss and wall panel plant"),
    "HOU-159": ("buyer", "Masonry contractor"),
    "HOU-158": ("buyer", "Masonry contractor"),
    "HOU-164": ("buyer", "Concrete contractor"),
    "HOU-153": ("buyer", "Light-gauge steel fabricator"),
    "HOU-113": ("buyer", "Tilt-up and structural concrete contractor"),
    "HOU-160": ("buyer", "Concrete pumping company"),
    "HOU-163": ("buyer", "Residential foundation contractor"),
    "HOU-148": ("buyer", "Wall panel and truss plant"),
    "HOU-118": ("client", "Shell contractor"),
    "HOU-115": ("client", "General contractor"),
    "HOU-111": ("buyer", "Concrete contractor"),
    "HOU-119": ("client", "General contractor, ICF and tilt-wall"),
    "HOU-109": ("buyer", "Concrete and civil contractor"),
    "HOU-107": ("buyer", "Site and concrete subcontractor"),
    "HOU-116": ("client", "General contractor"),
    "HOU-108": ("buyer", "Tilt-up and site concrete contractor"),
    "HOU-110": ("buyer", "Concrete and metal building contractor"),
    "HOU-006": ("client", "Apartment and mixed-use developer"),
    "HOU-072": ("buyer", "Custom homebuilder, build on your lot"),
    "HOU-083": ("client", "Retail and office developer"),
    "HOU-005": ("client", "Mixed-use developer"),
    "HOU-081": ("client", "Investment and development firm"),
    "HOU-036": ("client", "Mixed-use developer"),
    "HOU-037": ("client", "Adaptive-reuse developer"),
    "HOU-082": ("client", "Commercial developer"),
    "HOU-038": ("client", "Property manager"),
    "HOU-080": ("client", "Adaptive-reuse developer"),
    "HOU-132": ("client", "National homebuilder"),
    "HOU-167": ("client", "National homebuilder"),
    "HOU-009": ("client", "National homebuilder"),
    "HOU-134": ("client", "National homebuilder"),
    "HOU-014": ("client", "National homebuilder"),
    "HOU-012": ("client", "National homebuilder"),
    "HOU-008": ("client", "National homebuilder"),
    "HOU-025": ("client", "National homebuilder"),
    "HOU-024": ("client", "National homebuilder"),
    "HOU-023": ("client", "National homebuilder"),
    "HOU-013": ("client", "National homebuilder"),
    "HOU-034": ("client", "National homebuilder"),
    "HOU-011": ("land", "Masterplan developer"),
    "HOU-015": ("land", "Land developer"),
    "HOU-041": ("land", "Masterplan developer"),
    "HOU-133": ("land", "Masterplan developer"),
    "HOU-039": ("land", "Land developer"),
    "HOU-040": ("land", "Masterplan developer"),
    "HOU-043": ("land", "Land developer"),
    "HOU-166": ("client", "National homebuilder, Houston division"),
    "HOU-042": ("land", "Land developer, owned by Lennar"),
    "HOU-078": ("client", "Entry-level and move-up homebuilder, owned by Lennar"),
    # Dallas-Fort Worth
    "DFW-BTR-010": ("buyer", "Build-to-rent developer and builder"),
    "DFW-020": ("buyer", "Production homebuilder"),
    "DFW-032": ("buyer", "Production homebuilder"),
    "DFW-026": ("buyer", "Production homebuilder"),
    "DFW-027": ("buyer", "Production and custom homebuilder"),
    "DFW-BTR-001": ("buyer", "Single-family rental owner and builder"),
    "DFW-003b": ("buyer", "Townhome builder, a Green Brick brand"),
    "DFW-003d": ("buyer", "Single-family and townhome builder, a Green Brick brand"),
    "DFW-BTR-005": ("client", "Build-to-rent developer"),
    "DFW-014": ("buyer", "Move-up homebuilder, a Green Brick brand"),
    "DFW-045": ("buyer", "Production homebuilder"),
    "DFW-003c": ("buyer", "Luxury homebuilder, a Green Brick brand"),
    "DFW-003a": ("buyer", "Entry-level and move-up homebuilder, a Green Brick brand"),
    "DFW-079": ("buyer", "Production homebuilder"),
    "DFW-BTR-006": ("buyer", "Build-to-rent developer and builder"),
    "DFW-029": ("buyer", "Production homebuilder"),
    "DFW-078": ("buyer", "Townhome builder"),
    "DFW-BTR-008": ("buyer", "Build-to-rent builder and owner"),
    "DFW-037": ("buyer", "Family homebuilder"),
    "DFW-BTR-009": ("client", "Build-to-rent community"),
    "DFW-008": ("buyer", "Production homebuilder"),
    "DFW-023": ("buyer", "Semi-custom production homebuilder"),
    "DFW-035": ("buyer", "Villa and townhome builder"),
    "DFW-BTR-007": ("buyer", "Build-to-rent builder"),
    "DFW-043": ("buyer", "Semi-custom homebuilder"),
    "DFW-021": ("buyer", "Production homebuilder"),
    "DFW-034": ("buyer", "Production homebuilder"),
    "DFW-022": ("buyer", "Homebuilder and developer"),
    "DFW-031": ("buyer", "Homebuilder, owned by Partners in Building"),
    "DFW-044": ("buyer", "Production homebuilder"),
    "DFW-033": ("buyer", "Production homebuilder"),
    "DFW-038": ("buyer", "Entry-level homebuilder, an Ashton Woods brand"),
    "DFW-030": ("buyer", "Production homebuilder"),
    "DFW-081": ("buyer", "Move-up homebuilder"),
    "DFW-028": ("buyer", "Production homebuilder"),
    "DFW-024": ("buyer", "Luxury homebuilder, a Perry Homes brand"),
    "DFW-042": ("buyer", "Production homebuilder, a Dream Finders brand"),
    "DFW-073": ("buyer", "Luxury homebuilder"),
    "DFW-025": ("buyer", "Production and semi-custom homebuilder"),
    "DFW-TR-051": ("buyer", "ICF and concrete contractor"),
    "DFW-TR-074": ("buyer", "Wall panel and truss plant"),
    "DFW-TR-050": ("buyer", "ICF wall contractor"),
    "DFW-TR-092": ("buyer", "Exterior wall panel plant"),
    "DFW-TR-091": ("buyer", "Framing and interiors contractor"),
    "DFW-TR-040": ("buyer", "Masonry contractor"),
    "DFW-TR-093": ("buyer", "SIP envelope contractor"),
    "DFW-TR-012": ("buyer", "Building materials dealer"),
    "DFW-TR-010": ("buyer", "Truss and wall panel plant"),
    "DFW-TR-031": ("buyer", "Precast concrete plant"),
    "DFW-TR-026": ("buyer", "General contractor with its own concrete crews"),
    "DFW-TR-032": ("buyer", "Precast concrete plant"),
    "DFW-TR-085": ("buyer", "Residential foundation contractor"),
    "DFW-TR-064": ("buyer", "Tilt-up concrete contractor"),
    "DFW-TR-030": ("buyer", "Precast concrete plant"),
    "DFW-TR-002": ("buyer", "Residential concrete contractor"),
    "DFW-TR-086": ("buyer", "Masonry and stucco contractor"),
    "DFW-TR-083": ("buyer", "Residential masonry contractor"),
    "DFW-TR-081": ("buyer", "Masonry contractor"),
    "DFW-TR-084": ("buyer", "Foundation contractor"),
    "DFW-TR-089": ("buyer", "Masonry and stucco contractor"),
    "DFW-TR-082": ("buyer", "Masonry and stucco contractor"),
    "DFW-TR-088": ("buyer", "Masonry contractor"),
    "DFW-TR-042": ("buyer", "Masonry contractor"),
    "DFW-TR-079": ("buyer", "Tilt-up general contractor"),
    "DFW-TR-090": ("buyer", "Residential masonry contractor"),
    "DFW-TR-071": ("buyer", "Masonry contractor"),
    "DFW-TR-087": ("buyer", "Post-tension foundation company"),
    "DFW-TR-022": ("client", "General contractor"),
    "DFW-TR-020": ("buyer", "Tilt-up concrete contractor"),
    "DFW-TR-041": ("buyer", "Masonry and precast installer"),
    "DFW-TR-025": ("client", "Construction manager"),
    "DFW-TR-027": ("buyer", "Tilt-up and structural concrete contractor"),
    "DFW-TR-060": ("buyer", "Concrete pumping company"),
    "DFW-TR-023": ("buyer", "Structural concrete contractor"),
    "DFW-TR-024": ("client", "General contractor"),
    "DFW-TR-021": ("client", "General contractor"),
    "DFW-TR-001": ("buyer", "Residential foundation contractor"),
    "DFW-TR-011": ("buyer", "Truss and wall panel plant"),
    "DFW-047": ("buyer", "Custom homebuilder, SIP walls"),
    "DFW-048": ("buyer", "Custom homebuilder, build on your lot"),
    "DFW-001": ("client", "National homebuilder"),
    "DFW-007": ("client", "National homebuilder"),
    "DFW-061": ("buyer", "Production homebuilder, run from Houston"),
    "DFW-011": ("client", "National homebuilder"),
    "DFW-010": ("client", "National homebuilder"),
    "DFW-052": ("client", "National homebuilder"),
    "DFW-063": ("client", "National homebuilder, a PulteGroup brand"),
    "DFW-060": ("client", "National homebuilder"),
    "DFW-064": ("client", "Active-adult homebuilder, a PulteGroup brand"),
    "DFW-003": ("client", "National homebuilder and land developer"),
    "DFW-058": ("client", "National homebuilder"),
    "DFW-050": ("client", "National homebuilder"),
    "DFW-054": ("client", "National homebuilder"),
    "DFW-055": ("client", "National homebuilder"),
    "DFW-062": ("client", "National homebuilder"),
    "DFW-006": ("client", "National homebuilder"),
    "DFW-053": ("client", "National homebuilder"),
    "DFW-051": ("client", "National luxury homebuilder"),
    "DFW-009": ("client", "National homebuilder"),
    "DFW-059": ("client", "National homebuilder"),
    "DFW-CH-015": ("land", "Masterplanned community"),
    "DFW-CH-021": ("land", "Masterplan developer"),
    "DFW-CH-001": ("land", "Masterplan developer"),
    "DFW-CH-018": ("land", "Land developer"),
    "DFW-CH-003": ("land", "Land developer"),
    "DFW-CH-014": ("land", "Masterplan developer"),
    "DFW-CH-008": ("land", "Masterplanned community"),
    "DFW-CH-020": ("land", "Masterplanned community"),
    "DFW-CH-016": ("land", "Masterplanned community"),
    "DFW-CH-004": ("land", "Masterplanned community"),
    "DFW-CH-007": ("land", "Masterplanned community"),
    "DFW-CH-002": ("land", "Land developer"),
    "DFW-CH-011": ("land", "Masterplanned community"),
    "DFW-CH-019": ("land", "Masterplanned community"),
    "DFW-CH-009": ("land", "Masterplanned community"),
    "DFW-CH-017": ("land", "Masterplan developer"),
    "DFW-BTR-004": ("client", "Single-family rental owner"),
    "DFW-CH-012": ("land", "Masterplanned community"),
    "DFW-CH-010": ("land", "Masterplanned community"),
    "DFW-CH-005": ("land", "Masterplanned community"),
    "DFW-CH-013": ("land", "Masterplanned community"),
    "DFW-002": ("client", "National homebuilder"),
}

# The same firm on both decks: one role. Checked by apply().
SAME_FIRM = (
    ("HOU-001", "DFW-BTR-010"), ("HOU-010", "DFW-BTR-008"), ("HOU-022", "DFW-061"),
    ("HOU-033", "DFW-042"), ("HOU-075", "DFW-044"), ("HOU-072", "DFW-048"),
    ("HOU-132", "DFW-001"), ("HOU-167", "DFW-007"), ("HOU-023", "DFW-011"),
    ("HOU-013", "DFW-010"), ("HOU-009", "DFW-060"), ("HOU-012", "DFW-055"),
    ("HOU-008", "DFW-006"), ("HOU-025", "DFW-053"), ("HOU-024", "DFW-009"),
    ("HOU-014", "DFW-054"), ("HOU-166", "DFW-002"), ("HOU-133", "DFW-CH-001"),
    ("HOU-040", "DFW-CH-014"), ("HOU-146", "DFW-TR-074"), ("HOU-163", "DFW-TR-001"),
    ("HOU-156", "DFW-TR-040"), ("HOU-102", "DFW-TR-026"), ("HOU-142", "DFW-TR-032"),
    ("HOU-144", "DFW-TR-030"), ("HOU-141", "DFW-TR-031"), ("HOU-113", "DFW-TR-027"),
    ("HOU-160", "DFW-TR-060"), ("HOU-164", "DFW-TR-002"),
)

_KNOWN = {}


def apply(data, market):
    """Set role and kind on every card on the deck, and check the table covers it."""
    deck = [t for t in data["targets"] if t.get("group") != "out"]
    ids = {t["target_id"] for t in deck}
    prefix = "HOU-" if market == "hou" else "DFW-"
    listed = {k for k in KIND if k.startswith(prefix)}
    missing = sorted(ids - listed)
    stray = sorted(listed - ids)
    if missing or stray:
        raise SystemExit("roles.py: cards with no role %s, roles for cards not on the deck %s" % (missing, stray))
    for t in deck:
        role, kind = KIND[t["target_id"]]
        if role not in ROLES:
            raise SystemExit("roles.py: %s has role %r" % (t["target_id"], role))
        t["role"], t["kind"] = role, kind
        _KNOWN[t["target_id"]] = role
    data["role_labels"] = dict(ROLE_LABEL)
    data["role_notes"] = dict(ROLE_NOTE)
    for a, b in SAME_FIRM:
        if KIND[a][0] != KIND[b][0]:
            raise SystemExit("roles.py: %s and %s are one firm with two roles" % (a, b))
    return data
