# -*- coding: utf-8 -*-
"""The explicit reason behind each of the three screens, per firm.

Order is always (repeatability, wall share, innovation appetite).
Each phrase states the fact. No evaluative adjectives, no metaphor.
Required for every firm shown as a card. Firms in the "not a fit" table
carry their one-line verdict from screens.py instead.
"""

WHY = {
# ---- already buying printed walls
"HOU-002": ("80 homes on one 13-acre site.",
            "Detached single-family, $250,000 to $275,000.",
            "All 80 already committed to printing, with HiveASMBLD."),
"HOU-016": ("26 homes in San Leon, 23 of them printed.",
            "Detached, 1,000 to 2,100 sq ft.",
            "Built three conventionally, then committed the rest to printing."),
"HOU-017": ("One duplex. Two units.",
            "Attached party walls, about 1,727 sq ft per unit.",
            "Printed it in Harris County between March and June 2026."),

# ---- strong targets
"HOU-001": ("Five Texas projects under way, five to seven more in the pipeline.",
            "Low-rise detached and attached rental that it builds and holds.",
            "Six years building its own construction software, plus robotic site inspection."),
"HOU-007": ("1,300 homes across 14 new communities, 359 at Valley Ranch.",
            "Detached single-family from the $300,000s.",
            "Markets its own wall assembly, though it is refined stick framing, not a new method."),
"HOU-004": ("Three-storey townhomes repeated across inner Houston.",
            "Attached party walls on both sides, three storeys. The highest wall share here.",
            "Same owner commissioned OMA for POST Houston, on the commercial side of the business."),
"HOU-006": ("340 units at The Mill, 294 more at Aliana opening 2027.",
            "Mixed-use and wrap multifamily, so podium and structure take some of the cost.",
            "Financed a cross-laminated timber frame and calls it a rare alternative to steel and concrete."),
"HOU-009": ("1,200 homes on 318 acres, built from only 18 floor plans.",
            "Detached single-family from the low $200,000s.",
            "Record 112-day cycle and a 5 percent direct-cost cut, but no change of method."),
"HOU-008": ("1,000 homes at Trinity Landing on 45 to 60 foot lots.",
            "Detached single-family. Narrow lots raise wall count per acre.",
            "AI across the business and sub-110-day cycles. Nothing on wall systems."),
"HOU-005": ("Fifteen projects in one district, 218 units at Clock Tower.",
            "Low-rise mixed-use with retail and residential stacked.",
            "Commissioned Michael Hsu for Montrose Collective, four-street frontage, $104.75M financed."),
"HOU-035": ("Five developments in one neighbourhood since 2002.",
            "Low-rise affordable housing.",
            "Post-Harvey resilience framing, from Rice's Kinder Institute rather than its own marketing."),
"HOU-036": ("East River is 60 city blocks on one site, phased over decades.",
            "Low and mid-rise blocks, with office and retail in the mix.",
            "District-scale design ambition, but no specific method precedent was found."),
"HOU-028": ("346 units on one site at Fort Bend Town Center.",
            "Mid-rise multifamily, units 496 to 2,088 sq ft.",
            "Its own affiliates act as architect and general contractor, so nobody outside can veto a method."),

# ---- worth pursuing, one gap
"HOU-003": ("Cuney Homes runs five phases from 2025 to 2032.",
            "Low-rise public housing.",
            "No method statement on record. Federal procurement does reward cost and schedule."),
"HOU-014": ("More than 185 communities, entry-level product, head office in the metro.",
            "Entry-level detached. High wall share.",
            "Its Q2 2026 earnings call mentions method, labour and cycle time zero times."),
"HOU-024": ("Fourteen named Houston communities.",
            "Detached single-family.",
            "No firm-specific method evidence found."),
"HOU-010": ("10,800 rental homes across 115 communities.",
            "Single-family rental that it builds, owns and manages.",
            "No construction-method statement found anywhere."),
"HOU-022": ("20,000 homes since 2004, 1,600 closed in a single year.",
            "Detached single-family.",
            "Search ended early. Daiwa House owns a stake and is an industrialised builder, untested."),
"HOU-023": ("125,000 homes across 19 markets, Houston head office, 50 years.",
            "Detached single-family.",
            "Its 2026 supplier recognition covers insulation and fire-stopping, not the envelope."),
"HOU-013": ("More than 120 communities and 65,000 homes, locally owned.",
            "Detached single-family.",
            "Its own published definition of innovation is smart-home features and floor plans."),
"HOU-031": ("36 freestanding emergency centres and over 100 build-to-suits.",
            "Single-storey pad buildings. Wall-dominant.",
            "No method evidence found."),
"HOU-032": ("Repeat townhome communities across inner Houston.",
            "Attached three-storey townhomes.",
            "No method evidence found."),
"HOU-019": ("389 homes across two build-to-rent communities.",
            "Detached rental that it owns long term.",
            "No method evidence found."),
"HOU-027": ("156 units at Sunterra, 10,000 homes in the national brand.",
            "Detached homes and townhomes.",
            "No method evidence found."),
"HOU-011": ("11,400 acres at Bridgeland, 4,500 homes at The Woodlands Hills.",
            "Sells lots to builders. Only its commercial and multifamily arms buy walls.",
            "Its Q1 2026 call says nothing about construction technology, method or labour."),
"HOU-012": ("1,000 homes at Trinity Landing, three Houston land deals in six months.",
            "Detached single-family.",
            "The CEO cites shorter cycle time but not what enabled it."),
"HOU-018": ("A Town Center format repeated at five or more Houston sites.",
            "Single-storey retail shell, which already competes against cheap tilt-wall concrete.",
            "No method evidence found."),
"HOU-020": ("parcHAUS funds seven single-family rental communities across Texas.",
            "Detached single-family rental.",
            "No method evidence found."),
"HOU-025": ("A 240-home Houston build-to-rent community and a dedicated brand.",
            "Detached rental.",
            "Its Yardly retrospective cites input costs with no method detail."),
"HOU-021": ("186 homes on 35 acres, financed with Harrison Street.",
            "Detached rental, units 1,172 to 1,442 sq ft.",
            "Launch coverage is positioning and amenities only."),
"HOU-034": ("110 active communities.",
            "Detached single-family.",
            "Owner Sumitomo Forestry is a timber group, which may cut against a concrete wall."),
"HOU-026": ("314 homes in Conroe and 240 in Cypress.",
            "Single-storey detached rental.",
            "Its stated technology package is smart-home fittings, not structure."),
"HOU-033": ("Close to 100 communities, 55,000 homes company-wide.",
            "Detached single-family.",
            "No method evidence, and no named executive was found either."),
"HOU-030": ("Roughly 100 properties, with two new Houston-area land positions.",
            "Retail shells, which already compete against tilt-wall concrete.",
            "No method evidence found."),
"HOU-029": ("Nineteen markets, with an in-house construction arm.",
            "Mid-rise multifamily.",
            "No method evidence found."),
"HOU-045": ("Builder at Sienna, with four Texas divisions.",
            "Detached single-family.",
            "Search returned directory listings only."),
"HOU-044": ("156 and 210 units on two Katy sites about a mile apart.",
            "Duplexes, so party walls on one side.",
            "No method evidence found."),
"HOU-037": ("27 buildings across 55 acres since 2005.",
            "Adaptive reuse of existing buildings, so there is little new exterior wall to print.",
            "Twenty years of building inside awkward industrial structures."),
"HOU-047": ("More than 80 retail projects, two centres of about 108,000 sq ft.",
            "Retail shells, and recent Houston activity is buying rather than building.",
            "No method evidence found."),
"HOU-048": ("Nine named centres, 7.2 million sq ft.",
            "Retail shells. Current activity is leasing and management, not ground-up.",
            "No method evidence found."),
}

WHY["HOU-038"] = (
    "Two towers, one conversion each. Nothing repeats.",
    "Office to residential inside an existing frame. There is no new exterior wall to print.",
    "It is taking on a $50 million conversion of two landmark towers from 1927 and 1941, which is "
    "a harder build than anything a printer would be asked to do.",
)

WHY["HOU-042"] = (
    "Sells lots inside its own masterplans. Lennar builds the houses.",
    "The lots are the product. Any machine question belongs to Lennar, not to Friendswood.",
    "Its owner has already paid for an unproven method: Lennar built a hundred printed homes with "
    "ICON at Wolf Ranch in Georgetown.",
)

AXIS_TITLE = {
    "repeatability": "Repetition: builds the same plans, in one place",
    "machine_fit": "Printer fit: one or two printers would cover it",
    "innovation": "Track record: has paid for a new building method before",
}
VERDICT_WORD = {"clear": "Yes", "partial": "Partly", "fail": "No"}
